- stories/Atom/Navigation/Breadcrumb/Breadcrumb.jsx
- stories/Atom/Navigation/Breadcrumb/Breadcrumb.stories.mdx
- stories/Atom/Navigation/Breadcrumb/BreadcrumbLast.jsx
- stories/Atom/Navigation/Breadcrumb/breadcrumb.scss
- stories/Atom/Navigation/Language-switcher-row/LanguageSwitcherRow.jsx
- stories/Atom/Navigation/Language-switcher-row/LanguageSwitcherRow.scss
- stories/Atom/Navigation/Language-switcher-row/LanguageSwitcherRow.stories.mdx
- stories/Atom/Navigation/Loader/loader.jsx
- stories/Atom/Navigation/Loader/loader.scss
- stories/Atom/Navigation/Loader/loader.stories.mdx
- stories/Atom/Navigation/Menu-items/Menu-Items.jsx
- stories/Atom/Navigation/Menu-items/Menu-Items.scss
- stories/Atom/Navigation/Menu-items/Menu-Items.stories.mdx
- stories/Atom/Navigation/ProgressBarNavigation/ProgressBarNavigation.jsx
- stories/Atom/Navigation/ProgressBarNavigation/ProgressBarNavigation.scss
- stories/Atom/Navigation/ProgressBarNavigation/ProgressBarNavigation.stories.mdx
- stories/Atom/Navigation/Sidebar-second-level/sidebarsecondlevel.jsx
- stories/Atom/Navigation/Sidebar-second-level/sidebarsecondlevel.scss
- stories/Atom/Navigation/Sidebar-second-level/sidebarsecondlevel.stories.mdx
- stories/Atom/Navigation/Sidebar-with-arrow/SidebarWithArrow.jsx
- stories/Atom/Navigation/Sidebar-with-arrow/SidebarWithArrow.scss
- stories/Atom/Navigation/Sidebar-with-arrow/SidebarWithArrow.stories.mdx
- stories/Atom/Navigation/Sidebar/sidebar.scss
- stories/Atom/Navigation/Sidebar/sidebar.stories.mdx
- stories/Atom/Navigation/Sidebar/sidebarFirstLevel.jsx
- stories/Atom/Navigation/Sidebar/sidebarFirstLevelsimple.jsx
- stories/assets/scss/_mixins.scss
navigation atoms after conflicts resolve
> navigation atoms after conflicts resolve

- stories/Atom/Form/Checkbox/Checkbox.jsx
- stories/Atom/Form/Checkbox/Checkbox.stories.mdx
- stories/Atom/Form/Checkbox/checkbox.scss
- stories/Atom/Form/Radio/Radio.jsx
- stories/Atom/Form/Radio/Radio.stories.mdx
- stories/Atom/Form/Radio/radio.scss
- stories/assets/images/Icon/icon-check.svg
- stories/assets/scss/_mixins.scss
- stories/assets/scss/_variables.scss
- stories/assets/scss/style.scss
Checkbox and Radio atoms define after conflicts resolve.
> Checkbox Radio atom conflicts resolve

- stories/Atom/Lists/Descriptionlist.jsx
- stories/Atom/Lists/Lists.stories.mdx
- stories/Atom/Lists/Orderlist.jsx
- stories/Atom/Lists/Unorderlist.jsx
- stories/Atom/Lists/lists.scss
- stories/assets/scss/style.scss
Lists atoms define after conflicts resolve.
> Lists atom conflicts resolve

- stories/Atom/Form/Checkbox/Checkbox.stories.mdx
- stories/Atom/Form/Radio/Radio.stories.mdx
- stories/Atom/Global/Color/color.stories.mdx
- stories/Atom/Global/Icons/icon.stories.mdx
- stories/Atom/Global/Logo/logo.stories.mdx
- stories/Atom/Global/Spacing/spacing.stories.mdx
- stories/Atom/Images/Authorimage/Authorimages.stories.mdx
- stories/Atom/Images/Image/Image.stories.mdx
- stories/Atom/Images/Imagecredit/Imagecredit.stories.mdx
- stories/Atom/Lists/Lists.stories.mdx
- stories/Atom/Reach-element/Details/details.stories.mdx
- stories/Atom/Reach-element/Figcaption/figcaption.stories.mdx
- stories/Atom/Reach-element/Progressbar/progress_bar.stories.mdx
- stories/Atom/Reach-element/Table/table.stories.mdx
> UNDP-3-4-5-6-12-13-31-34 documentation updated

- stories/Atom/Buttons-and-labels/Chips/chips.jsx
- stories/Atom/Buttons-and-labels/Chips/chips.scss
- stories/Atom/Buttons-and-labels/Chips/chips.stories.mdx
- stories/Atom/Buttons-and-labels/Chips/chips_cross.jsx
- stories/Atom/Buttons-and-labels/Cta_button/buttons.scss
- stories/Atom/Buttons-and-labels/Cta_button/buttons.stories.mdx
- stories/Atom/Buttons-and-labels/Cta_button/cta_link_arrow.jsx
- stories/Atom/Buttons-and-labels/Cta_button/cta_link_space.jsx
- stories/Atom/Buttons-and-labels/Cta_button/primary_button_arrow.jsx
- stories/Atom/Buttons-and-labels/Cta_button/primary_button_arrow_disbled.jsx
- stories/Atom/Buttons-and-labels/Cta_button/primary_button_noarrow.jsx
- stories/Atom/Buttons-and-labels/Cta_button/primary_button_noarrow_disbled.jsx
- stories/Atom/Buttons-and-labels/Cta_button/secondary_button.jsx
- stories/Atom/Buttons-and-labels/Cta_button/secondary_button_disabled.jsx
- stories/assets/images/Icon/Search_black.svg
- stories/assets/images/Icon/Searchgray.svg
- stories/assets/images/Icon/Timesred.svg
- stories/assets/images/Icon/chevron-right-black.svg
- stories/assets/images/Icon/chevron-right-white.svg
- stories/assets/scss/_mixins.scss
Buttons and labels were created.
> Buttons atom defined

- stories/Atom/Base-typography/Abbr/abbr.stories.mdx
- stories/Atom/Base-typography/Blockquote/blockquote.stories.mdx
- stories/Atom/Base-typography/Cite/cite.stories.mdx
- stories/Atom/Base-typography/Code/code.stories.mdx
- stories/Atom/Base-typography/Heading/heading.stories.mdx
- stories/Atom/Base-typography/Hr/hr.stories.mdx
- stories/Atom/Base-typography/Link/link.stories.mdx
- stories/Atom/Base-typography/Mark/mark.stories.mdx
- stories/Atom/Base-typography/Paragraph/p.stories.mdx
- stories/Atom/Base-typography/Quotation/quotation.stories.mdx
- stories/Atom/Base-typography/Small/small.stories.mdx
> Worked on documentation

- stories/Molecules/Imagecaption/imagecaption.scss
> RTL issue resolved

- stories/Molecules/Text/Page/Page.jsx
- stories/Molecules/Text/Page/Page.stories.mdx
- stories/Molecules/Text/Page/page.scss
> UND-15 page block white

- stories/Molecules/Text/Page/Page.stories.mdx
- stories/Molecules/Text/Post/Post.jsx
- stories/Molecules/Text/Post/Post.stories.mdx
> Accessibility Issue

- stories/Atom/Input-group/input_group.scss
- stories/Atom/Input-group/input_group.stories.mdx
- stories/Atom/Input-group/tel_input.jsx
- stories/Atom/Input-group/textarea_input.jsx
bug fixing for tickets UNDP-102, 103, 104, 105, 110
> Bug Fixing

- stories/Molecules/Text/Page/Page.stories.mdx
UND-100-Accessibility-Issue-bg post block bg color
> UND-100-Accessibility-Issue-bg

- stories/Molecules/Text/ProjectDetails/ProjectDetails.jsx
- stories/Molecules/Text/ProjectDetails/ProjectDetails.stories.mdx
- stories/Molecules/Text/ProjectDetails/projectdetails.scss
- stories/Molecules/Text/SmallCopy/SmallCopy.jsx
- stories/Molecules/Text/SmallCopy/SmallCopy.stories.mdx
- stories/Molecules/Text/SmallCopy/smallcopy.scss
- stories/assets/scss/style.scss
Define small copy lockup and project details column
> Small copy and Project details define

- stories/Molecules/Imagecaption/Imagecaption.stories.mdx
- stories/Molecules/Imagecaption/imagecaption.scss
This PR fixed the issue on the image atom. These issues were happening from the image molecules scss file.
> Fixed the desktop and mobile issue

- stories/Atom/Base-typography/Heading/h5.jsx
- stories/Molecules/Text/Faq/Faq.jsx
- stories/Molecules/Text/Faq/Faq.scss
- stories/assets/js/Faq_custom.js
> Accordion Issue toggle

- stories/Molecules/Text/SmallCopy/SmallCopy.stories.mdx
- stories/Molecules/Text/SmallCopy/smallcopy.scss
This PR fixed the location and rtl issue.
> Fixed the location and rtl

- stories/Atom/Navigation/Breadcrumb/Breadcrumb.jsx
- stories/Atom/Navigation/Breadcrumb/Breadcrumb.stories.mdx
- stories/Atom/Navigation/Breadcrumb/BreadcrumbLast.jsx
- stories/Atom/Navigation/Breadcrumb/breadcrumb.scss
Breadcrumb jsx extra files files remove
> Breadcrumb jsx files

- stories/Atom/Input-group/date_input.jsx
- stories/Atom/Input-group/input_group.scss
Added black color for error state- textarea
> Added black color for errorstate-textarea

- stories/Molecules/Text/Faq/Faq.scss
this issue is genrated on the actual device.
> UND-123-Accordion-RTL-arabic

- stories/Atom/Buttons-and-labels/Chips/chips.scss
- stories/Atom/Buttons-and-labels/Cta_button/buttons.scss
- stories/Atom/Buttons-and-labels/Cta_button/buttons.stories.mdx
- stories/assets/scss/_mixins.scss
Fixed spacing issue and created mixins.
> Fixed rtl issue

- stories/Atom/Buttons-and-labels/Cta_button/cta_link_arrow.jsx
Added javascript:void(0) in href  insted of #
> Changed # with js void

- stories/Molecules/Text/Faq/Faq.scss
icon switch according to RTL as a mirror
> accordion-ltr

- stories/Molecules/Blocks/SingleContent/SingleContent.jsx
- stories/Molecules/Blocks/SingleContent/SingleContent.stories.mdx
- stories/Molecules/Blocks/SingleContent/singlecontent.scss
- stories/assets/scss/style.scss
Define blocks single content card molecule
> Blocks Single Content Card

- stories/Molecules/Blocks/StatsCards/StatsCards.jsx
- stories/Molecules/Blocks/StatsCards/StatsCards.stories.mdx
- stories/Molecules/Blocks/StatsCards/statscards.scss
- stories/assets/scss/_typography.scss
- stories/assets/scss/_variables.scss
- stories/assets/scss/style.scss
Define stats cards molecules on different widths
> Stats Cards Molecules

- stories/Atom/Navigation/Menu-items/Menu-Items.jsx
- stories/Atom/Navigation/Menu-items/Menu-Items.scss
- stories/Molecules/Navbar/Breadcrumb/Breadcrumb-link.jsx
- stories/Molecules/Navbar/Breadcrumb/Breadcrumb-link.stories.mdx
- stories/Molecules/Navbar/Breadcrumb/breadcrumb-link.scss
- stories/Molecules/Navbar/Menu/Menu.jsx
- stories/Molecules/Navbar/Menu/Menu.stories.mdx
- stories/Molecules/Navbar/Menu/menu.scss
- stories/assets/scss/style.scss
Created navbar for breadcrumb and menu and made some minor changes in Menu-Items.jsx and menu-Items.scss file as required
> Created Navbar-breadcrumb, menu

- stories/Molecules/FooterNavigation/FooterConditions/FooterConditions.stories.mdx
- stories/Molecules/FooterNavigation/FooterConditions/footerCondition.scss
- stories/Molecules/FooterNavigation/FooterConditions2/footerCondition2.scss
- stories/Molecules/FooterNavigation/FooterIcons/footerIcons.scss
- stories/assets/scss/style.scss
> footer nav issue

- stories/Atom/Lists/Lists.jsx
- stories/Molecules/Text/Authors/Authorcard/Authorcard.jsx
- stories/Molecules/Text/Authors/Authorcard/Authorcard.stories.mdx
- stories/Molecules/Text/Authors/Authorcard/authorcard.scss
- stories/Molecules/Text/Authors/Authorcolumn/Authors.jsx
- stories/Molecules/Text/Authors/Authorcolumn/Authors.stories.mdx
- stories/Molecules/Text/Authors/Authorcolumn/authors.scss
- stories/assets/scss/style.scss
Define Author Molecules with different columns and with cards.
> Authors Molecules

- stories/Molecules/Blocks/ImageRevelCard/ImageCard.stories.mdx
- stories/Molecules/Blocks/ImageRevelCard/imagecard.scss
Added hover effect on the whole card and change language for other language
> Added hover effect

- stories/Molecules/Navbar/Pagination/Pagination.jsx
- stories/Molecules/Navbar/Pagination/Pagination.stories.mdx
- stories/Molecules/Navbar/Pagination/pagination.scss
- stories/Molecules/Navbar/Tab/Tab.jsx
- stories/Molecules/Navbar/Tab/Tab.stories.mdx
- stories/Molecules/Navbar/Tab/tab.scss
- stories/assets/js/Tab_custom.js
> UND-70-Tab-Pagination

- stories/Molecules/Navbar/Breadcrumb/Breadcrumb-link.jsx
- stories/Molecules/Navbar/Tab/Tab.jsx
- stories/Molecules/Navbar/Tab/Tab.stories.mdx
- stories/Molecules/Text/Post/Post.jsx
- stories/Organism/Text/PostHeader/PostHeader.jsx
- stories/Organism/Text/PostHeader/PostHeader.stories.mdx
- stories/Organism/Text/PostHeader/postheader.scss
- stories/assets/scss/style.scss
> Undp 17 organism text

- stories/Atom/Navigation/Scroll-bar/ScrollBar.jsx
- stories/Atom/Navigation/Scroll-bar/ScrollBar.stories.mdx
- stories/Atom/Navigation/Scroll-bar/scrollbar.scss
- stories/assets/scss/_base.scss
> scroll bar

- stories/Molecules/Multiselect/multiselect.scss
Added default white color for the background.
> Added default color

- stories/Atom/Images/FrostedImage/FrostedImage.jsx
- stories/Atom/Images/FrostedImage/FrostedImage.stories.mdx
- stories/Atom/Images/FrostedImage/frostedimage.scss
Added Frosted overlay on an image
> Added frosted overlay

- stories/Organism/Images/Images/Images.stories.mdx
- stories/Organism/Images/Images/images.scss
Fixed the portrait desktop view.
> Fixed the Portrait UI

- stories/Organism/Blocks/Heros/Global-Homepage-Hero/HomepageHero.jsx
- stories/Organism/Blocks/Heros/Global-Homepage-Hero/HomepageHero.stories.mdx
- stories/Organism/Blocks/Heros/Global-Homepage-Hero/homepagehero.scss
- stories/Organism/Blocks/Heros/Internal-Page-Heros/PageHero.jsx
- stories/Organism/Blocks/Heros/Internal-Page-Heros/PageHero.stories.mdx
- stories/Organism/Blocks/Heros/Internal-Page-Heros/pagehero.scss
- stories/assets/js/animation.js
- stories/assets/scss/_base.scss
- stories/assets/scss/_mixins.scss
Fixed the scroll animation , and rtl animation.
> Add scroll animation hero organisms

- stories/Atom/Images/Authorimage/Authorimages.jsx
- stories/Atom/Images/Authorimage/Authorimages.stories.mdx
- stories/Molecules/Text/Authors/Authorcard/Authorcard.jsx
- stories/Molecules/Text/Authors/Authorcard/Authorcard.stories.mdx
- stories/Molecules/Text/Authors/Authorcolumn/Authors.jsx
- stories/Molecules/Text/Authors/Authorcolumn/Authors.stories.mdx
- stories/Molecules/Text/Authors/Authorcolumn/authors.scss
- stories/Organism/Blocks/Authorcard/AuthorSummary.jsx
- stories/Organism/Blocks/Authorcard/AuthorSummary.stories.mdx
- stories/Organism/Blocks/Authorcard/authorsummary.scss
created author card summary and made changes on authorcard  and authorcard column files as required
> Created authorcard summary

- stories/Atom/Navigation/Scroll-bar/scrollbar.scss
- stories/Molecules/Blocks/CountryCard/countrycard.scss
- stories/Molecules/Blocks/Lightbox/Lightbox.stories.mdx
- stories/Molecules/Blocks/Lightbox/lightbox.scss
lightbox and scroll and countryard issue
> lightbox and scroll and countryard issue

- stories/Organism/Blocks/Authorcard/AuthorSummary.jsx
- stories/Organism/Blocks/Authorcard/authorsummary.scss
Added spacing for author summary component
> Added spacing for author-summary

- stories/Molecules/Imagecaption/imagecaption.scss
> Fixed credit placement

- stories/Organism/Blocks/FeaturedContentCard/PagewideContentCard/pagewidecard.scss
Added Spacing for  RTL in page-wide component
> Added spacing for pagewide in rtl

- stories/Molecules/DownloadRow/DownloadRow.jsx
- stories/Molecules/DownloadRow/DownloadRow.stories.mdx
- stories/Molecules/DownloadRow/downloadrow.scss
- stories/Organism/Images/Images/Images.stories.mdx
- stories/assets/scss/style.scss
> Added download row

- stories/Molecules/Multiselect/MultiSelect.jsx
- stories/Molecules/Multiselect/MultiSelect.stories.mdx
- stories/Organism/FilterAndSearchBar/FilterAndSearchBar.jsx
- stories/Organism/FilterAndSearchBar/FilterAndSearchBar.scss
- stories/Organism/FilterAndSearchBar/FilterAndSearchBar.stories.mdx
- stories/assets/js/FilterAndSearchBar.js
Made the changes as per your suggestion
> Make changes as per suggestion

- stories/Molecules/Blocks/BioCard/BioCard.jsx
- stories/Molecules/Blocks/BioCard/biocard.scss
> bio card issues

- stories/Molecules/Blocks/FeaturedContentCard/FeaturedContentCard.jsx
- stories/Molecules/Blocks/FeaturedContentCard/featuredContentCard.scss
- stories/Molecules/Blocks/SingleContent/SingleContent.jsx
- stories/Molecules/Blocks/SingleContent/SingleContent.stories.mdx
- stories/Molecules/Blocks/SingleContent/singlecontent.scss
- stories/Organism/Blocks/FeaturedContentCard/FeaturedCard/featuredcard.scss
Added spacing and other styling
> Added spacing

- stories/Molecules/FooterNavigation/FooterConditions/FooterConditions.jsx
- stories/Molecules/FooterNavigation/FooterConditions/FooterConditions.stories.mdx
- stories/Molecules/FooterNavigation/FooterConditions/footerCondition.scss
- stories/Molecules/FooterNavigation/FooterConditions2/FooterConditions2.jsx
- stories/Molecules/FooterNavigation/FooterConditions2/FooterConditions2.stories.mdx
- stories/Molecules/FooterNavigation/FooterConditions2/footerCondition2.scss
- stories/Molecules/FooterNavigation/FooterIcons/footerIcons.scss
- stories/Molecules/FooterNavigation/FooterLists/FooterLists.jsx
- stories/Molecules/FooterNavigation/FooterLists/footerLists.scss
- stories/Molecules/Form/SignUp.jsx
- stories/Molecules/Form/SignUp.stories.mdx
- stories/Molecules/Form/signup.scss
- stories/Organism/Footer/Footer.jsx
- stories/Organism/Footer/Footer.stories.mdx
- stories/Organism/Footer/FooterTwo.jsx
- stories/Organism/Footer/footer.scss
- stories/assets/js/accordion_custom.js
- stories/assets/scss/_mixins.scss
> Footer Navigation

- stories/Molecules/FooterNavigation/FooterConditions2/footerCondition2.scss
- stories/Organism/Footer/Footer.jsx
- stories/Organism/Footer/Footer.stories.mdx
- stories/Organism/Footer/footer.scss
> Fixed spacing issue

- .gitignore
- stories/Components/StatsSlider/StatsSlider.jsx
- stories/Components/StatsSlider/statsslider.scss
- stories/assets/js/SliderCustom.js
> Und 310 stats slider

- stories/Molecules/Text/Authors/Authorcard/Authorcard.jsx
- stories/Molecules/Text/Authors/Authorcard/Authorcard.stories.mdx
- stories/Molecules/Text/Authors/Authorcard/authorcard.scss
- stories/Molecules/Text/SmallCopy/SmallCopy.jsx
- stories/Molecules/Text/SmallCopy/SmallCopy.stories.mdx
- stories/Molecules/Text/SmallCopy/smallcopy.scss
Update author card and small copy component
> update html and font size

- stories/Atom/Images/Imagecredit/Imagecredit.jsx
- stories/Atom/Images/Imagecredit/Imagecredit.stories.mdx
- stories/Atom/Images/Imagecredit/imagecredit.scss
- stories/Molecules/Blocks/SingleContent/SingleContent.jsx
- stories/Molecules/Blocks/SingleContent/singlecontent.scss
- stories/Molecules/Blocks/StatsCards/StatsCards.jsx
- stories/Molecules/Blocks/StatsCards/statscards.scss
- stories/Molecules/Imagecaption/Imagecaption.jsx
- stories/Molecules/Imagecaption/Imagecaption.stories.mdx
- stories/Molecules/Imagecaption/imagecaption.scss
- stories/Organism/Images/Images/Images.jsx
- stories/Organism/Images/Images/Images.stories.mdx
- stories/Organism/Images/Images/images.scss
Update HTML and CSS for image credit, single content card, and stats card
> Update css and html

- .gitignore
- stories/Molecules/Blocks/StatsPanel/StatsPanel.jsx
- stories/Organism/Stats/Stats.jsx
- stories/Organism/Stats/Stats.stories.mdx
- stories/Organism/Stats/stats.scss
- stories/assets/js/Stats-custom.js
- stories/assets/js/viewport.js
- stories/assets/scss/_base.scss
> Und 276 stats grid

- stories/Atom/Navigation/Breadcrumb/Breadcrumb.jsx
- stories/Atom/Navigation/Breadcrumb/breadcrumb.scss
- stories/Atom/Reach-element/Table/table.jsx
- stories/Atom/Reach-element/Table/table.scss
- stories/Atom/Reach-element/Table/table.stories.mdx
- stories/Molecules/Navbar/Breadcrumb/Breadcrumb-link.jsx
- stories/Molecules/Navbar/Breadcrumb/breadcrumb-link.scss
Update table atom and breadcrumb molecule
> Update table and breadcrumb

- stories/Atom/Images/Imagecredit/Imagecredit.stories.mdx
- stories/Molecules/Blocks/StatsCards/statscards.scss
- stories/Molecules/Imagecaption/imagecaption.scss
Update image credit placement and line-height for extra-large stats card
> Update placement for image caption

- .storybook/preview-head.html
- stories/Molecules/Blocks/CountryCard/CountryCard.jsx
- stories/Molecules/Blocks/CountryCard/countrycard.scss
- stories/Organism/Blocks/Heros/Country-Card-Hero/CountryCardHero.jsx
- stories/Organism/Blocks/Heros/Country-Card-Hero/CountryCardHero.stories.mdx
- stories/Organism/Blocks/Heros/Country-Card-Hero/countrycardhero.scss
- stories/Organism/Blocks/Heros/Global-Homepage-Hero/HomepageHero.stories.mdx
- stories/Organism/Blocks/Heros/Internal-Page-Heros/PageHero.stories.mdx
- stories/assets/js/SliderCustom.js
- stories/assets/js/smartresize.js
- stories/assets/scss/_base.scss
> Country Level Mobile

- stories/Molecules/Text/Authors/Authorcard/authorcard.scss
- stories/Molecules/Text/Authors/Authorcolumn/authors.scss
- stories/Molecules/Text/SmallCopy/SmallCopy.jsx
- stories/Molecules/Text/SmallCopy/smallcopy.scss
Added line-height for author role and bio text and text-transform property for all authors
> Molecule-author-spacing-bug

- stories/Molecules/Blocks/ContentCard/ContentCardImage.jsx
- stories/Molecules/Blocks/ContentCard/ContentCardImage.stories.mdx
- stories/Molecules/Blocks/ContentCard/ContentCardWithOutImage.jsx
- stories/Molecules/Blocks/ContentCard/ContentCardWithOutImage.stories.mdx
- stories/Molecules/Blocks/ContentCard/contentcard.scss
- stories/Organism/Blocks/ContentCard/ContentCard.jsx
> content card update

- stories/Atom/Cards/Publication-thumbnail/PublicationThumbnail.jsx
- stories/Atom/Cards/Publication-thumbnail/publication-thumbnail.scss
- stories/Components/Carousels/FixedImageSizeCarousel/FixedImageSizeCarousel.jsx
- stories/Components/Carousels/FixedImageSizeCarousel/FixedImageSizeCarousel.stories.mdx
- stories/Components/Carousels/FixedImageSizeCarousel/fixedimagesizecarousel.scss
- stories/Components/StatsSlider/StatsSlider.jsx
- stories/Components/StatsSlider/statsslider.scss
- stories/Organism/Blocks/Heros/Country-Card-Hero/CountryCardHero.jsx
- stories/assets/js/Carousel.js
- stories/assets/scss/_base.scss
- stories/assets/scss/_glideslider.scss
> Fixed image size carousel

- stories/Atom/Global/Icons/search_black.jsx
- stories/Molecules/Multiselect/MultiSelect.jsx
- stories/Molecules/Multiselect/MultiSelect.stories.mdx
- stories/Molecules/Multiselect/multiselect.scss
- stories/Organism/FilterAndSearchBar/FilterAndSearchBar.jsx
- stories/Organism/FilterAndSearchBar/FilterAndSearchBar.scss
- stories/Organism/FilterAndSearchBar/FilterAndSearchBar.stories.mdx
- stories/assets/js/FilterAndSearchBar.js
create new branch due to conflict issue on previous 287.
> create new branch due to conflict issue.

- stories/Molecules/FooterNavigation/FooterIcons/FooterIcons.jsx
- stories/Molecules/FooterNavigation/FooterIcons/footerIcons.scss
- stories/Organism/Blocks/Heros/Country-Card-Hero/countrycardhero.scss
- stories/Organism/Blocks/ParallaxCard/ParallaxCards.jsx
- stories/Organism/Blocks/ParallaxCard/parallaxcards.scss
- stories/Organism/Footer/Footer.jsx
- stories/Organism/Footer/FooterTwo.jsx
- stories/Organism/Footer/footer.scss
Fixed parallax card slider, country card slider, footer color text
> Fixed Footer countrycard parallax

- stories/Atom/Reach-element/Table/table.scss
- stories/Molecules/Blocks/FeaturedContentCard/FeaturedContentCard.jsx
- stories/Molecules/Blocks/FeaturedContentCard/FeaturedContentCard.stories.mdx
- stories/Molecules/Blocks/FeaturedContentCard/featuredContentCard.scss
- stories/Molecules/Blocks/ImageRevelCard/imagecard.scss
- stories/Molecules/Navbar/Breadcrumb/breadcrumb-link.scss
Added scroll, update image reveal card, and heading condition on the featured content card.
> Added scroll and update image reveal card

- stories/Components/DownloadModal/DownloadModal.jsx
- stories/Components/DownloadModal/downloadmodal.scss
- stories/Molecules/Blocks/ImageRevelCard/imagecard.scss
- stories/Molecules/CustomSelect/customselect.scss
- stories/Molecules/DownloadRow/downloadrow.scss
- stories/Molecules/FooterNavigation/FooterConditions2/footerCondition2.scss
> Download Modal fixed issues

- stories/Atom/Global/Icons/back.jsx
- stories/Atom/Global/Icons/icon_Times_Blue.jsx
- stories/Molecules/Navbar/Menu/Menu.jsx
- stories/Molecules/Navbar/Menu/menu.scss
- stories/Organism/Navigation/GlobalHeader/GlobalHeader.jsx
- stories/Organism/Navigation/GlobalHeader/GlobalHeader.scss
- stories/Organism/Navigation/GlobalHeader/GlobalHeader.stories.mdx
- stories/assets/images/Icon/Times-blue.svg
- stories/assets/images/Icon/back.svg
- stories/assets/js/navigation.js
- stories/assets/js/navigationData.json
- stories/assets/scss/_breakpoints.scss
> UND-52-GlobalHeader

- stories/Atom/Reach-element/Table/table.scss
> Added webkit for text size

- stories/Molecules/Text/Authors/Authorcolumn/Authors.jsx
- stories/Organism/Articlepage/ArticlePage.jsx
- stories/Organism/Articlepage/ArticlePage.scss
- stories/Organism/Articlepage/ArticlePage.stories.mdx
Create a new branch due to build issue on und-67.
> und-67-new

- stories/Atom/Reach-element/Table/table.jsx
- stories/Molecules/FooterNavigation/FooterConditions2/footerCondition2.scss
- stories/Organism/Footer/FooterTwo.jsx
- stories/Organism/Footer/footer.scss
> Fixed RTL issue in footer

- stories/Organism/Navigation/CountrySiteHeader/CountrySiteHeader.jsx
- stories/Organism/Navigation/CountrySiteHeader/CountrySiteHeader.scss
- stories/Organism/Navigation/CountrySiteHeader/CountrySiteHeader.stories.mdx
- stories/assets/scss/_breakpoints.scss
Create new branch due to build issue on und-53
> und-53-new

- stories/Templates/LandingPage/GenericLandingPage.jsx
- stories/Templates/LandingPage/genericlandingpage.scss
> issue resolved

- stories/Components/UIcomponents/Carousel/FixedSizeCarousel/FixedSizeCarousel.jsx
- stories/Components/UIcomponents/Carousel/FixedSizeCarousel/fixedsizecarousel.scss
- stories/Components/UIcomponents/Carousel/FluidImageSizeCarousel/FluidImageSizeCarousel.jsx
- stories/Components/UIcomponents/Carousel/FluidImageSizeCarousel/fluidimagesizecarousel.scss
- stories/Components/UIcomponents/Carousel/ImageOnlyCarousel/ImageOnlyCarousel.jsx
- stories/Components/UIcomponents/Carousel/ImageOnlyCarousel/imageonlycarousel.scss
- stories/assets/js/Carousel.js
- stories/assets/scss/_base.scss
- stories/assets/scss/_mixins.scss
> Carousel bug fixing

- stories/Templates/Articlepage/ArticlePage.jsx
- stories/Templates/Articlepage/ArticlePage.scss
- stories/assets/scss/normalize.scss
> article change

- stories/Templates/LandingPage/GenericLandingPage.jsx
Accessibility Violations resolved
> Accessibility Violations resolved

- stories/Components/UIcomponents/Hero/Homepagehero/HomepageHero.stories.mdx
- stories/Components/UIcomponents/Hero/Homepagehero/HomepageHeroOption.jsx
- stories/Components/UIcomponents/Hero/Homepagehero/homepagehero.scss
Updated Homepage hero - Wide image
> homepage hero wide image

- stories/Components/UIcomponents/Cards/StatsCards/statscards.scss
- stories/Molecules/Blocks/StatsPanel/StatsPanel.jsx
- stories/Molecules/Blocks/StatsPanel/StatsPanel.stories.mdx
- stories/Molecules/Blocks/StatsPanel/statspanel.scss
- stories/Organism/Stats/Stats.jsx
- stories/Organism/Stats/Stats.stories.mdx
Added transition of stats panel molecule and updated story name of stats panel
> Added transition

- stories/Molecules/Text/TextCta/TextCta.jsx
- stories/Molecules/Text/TextCta/TextCta.stories.mdx
- stories/Molecules/Text/TextCta/textcta.scss
> added textcta molecule

- stories/Molecules/Text/TextBackground/TextBackground.jsx
- stories/Molecules/Text/TextBackground/TextBackground.stories.mdx
- stories/Molecules/Text/TextBackground/textbackground.scss
created Text + Background molecule
> added text background molecule

- stories/Patterns/StatsSlider/statsslider.scss
- stories/assets/js/SliderCustom.js
> fixed RTL animation issue

- stories/Components/UIcomponents/Hero/Homepagehero/HomepageHeroOption.jsx
- stories/Components/UIcomponents/Hero/Homepagehero/homepagehero.scss
- stories/Molecules/Blocks/PublicationCard/PublicationCard.jsx
- stories/Molecules/Blocks/PublicationCard/PublicationCard.stories.mdx
- stories/Molecules/Blocks/PublicationCard/publicationcard.scss
- stories/Templates/GenericPage/GenericPage.jsx
- stories/Templates/GenericPage/genericpage.scss
- stories/Templates/LandingPage/GenericLandingPage.jsx
- stories/Templates/LandingPage/genericlandingpage.scss
- stories/Templates/PublicationPage/PublicationPage.jsx
- stories/Templates/PublicationPage/PublicationPage.stories.mdx
- stories/Templates/PublicationPage/publicationpage.scss
- stories/assets/js/sticky.js
> Publication page template

- stories/Templates/GenericPage/GenericPage.jsx
- stories/Templates/GenericPage/GenericPage.stories.mdx
- stories/Templates/GenericPage/genericpage.scss
> UND-534 issues resolved

- stories/Molecules/Blocks/TweetCard/TweetCard.jsx
- stories/Molecules/Blocks/TweetCard/TweetCard.stories.mdx
- stories/Molecules/Blocks/TweetCard/tweetcard.scss
- stories/Organism/Blocks/TweetPanel/TweetPanel.jsx
- stories/Organism/Blocks/TweetPanel/TweetPanel.stories.mdx
- stories/Organism/Blocks/TweetPanel/tweetpanel.scss
Added animation and spacing for Twitter icon
> Worked on animation and spacing

- stories/Components/Forms/Dropdowns/Multiselect/multiselect.scss
- stories/Components/Navigationcomponents/Pagination/Pagination.jsx
- stories/Components/Navigationcomponents/Pagination/pagination.scss
- stories/Components/UIcomponents/Tab/Tab.jsx
- stories/Components/UIcomponents/Tab/tab.scss
- stories/assets/js/Tab_custom.js
> UND-475-issue

- stories/Molecules/ParallaxCard/ParallaxCard.jsx
Update HTML for parallax card.
> Update html for parallax

- stories/Components/Forms/Inputfields/Input_group.jsx
- stories/Components/Forms/Inputfields/input_group.stories.mdx
- stories/Components/Forms/SearchBox/Searchbox.jsx
- stories/Components/Forms/SearchBox/Searchbox.stories.mdx
- stories/Components/Navigationcomponents/Breadcrumbs/Breadcrumbs.jsx
- stories/Components/Navigationcomponents/Breadcrumbs/Breadcrumbs.stories.mdx
- stories/Components/UIcomponents/Author/Authorcard/Authorcard.jsx
- stories/Components/UIcomponents/Author/Authorcard/Authorcard.stories.mdx
- stories/Components/UIcomponents/Author/Authorcolumn/Authors.jsx
- stories/Components/UIcomponents/Author/Authorcolumn/Authors.stories.mdx
- stories/Components/UIcomponents/Author/Authorcolumn/authors.scss
- stories/Components/UIcomponents/Buttons/Chips/chips.jsx
- stories/Components/UIcomponents/Buttons/Chips/chips.stories.mdx
- stories/Components/UIcomponents/Buttons/Cta_button/CtaButton.jsx
- stories/Components/UIcomponents/Buttons/Cta_button/CtaButton.stories.mdx
- stories/Components/UIcomponents/Buttons/Cta_link/Cta_link.jsx
- stories/Components/UIcomponents/Buttons/Cta_link/Cta_link.stories.mdx
- stories/Components/UIcomponents/Cards/ImageRevelCTACard/ImageCard.jsx
- stories/Components/UIcomponents/Cards/ImageRevelCTACard/ImageCard.stories.mdx
- stories/Components/UIcomponents/Cards/StatsCards/StatsCards.jsx
- stories/Components/UIcomponents/Cards/StatsCards/StatsCards.stories.mdx
Reverts undp/design-system#239
> Revert "Und 529 authors"

- .storybook/preview.js
- stories/Components/Forms/expandable search/SearchExpand.jsx
- stories/Components/Forms/expandable search/SearchExpand.stories.mdx
- stories/Components/Navigationcomponents/Breadcrumbs/Breadcrumbs.stories.mdx
- stories/Components/UIcomponents/Buttons/Chips/chips.stories.mdx
- stories/Components/UIcomponents/Buttons/Cta_button/CtaButton.stories.mdx
- stories/Molecules/Blocks/TweetCard/TweetCard.stories.mdx
- stories/Organism/Blocks/TweetPanel/TweetPanel.stories.mdx
- stories/Utilities/Loader/loader.stories.mdx
> tree structure update

- stories/Components/UIcomponents/Cards/ContentCard/ContentCardImage.jsx
- stories/Components/UIcomponents/Cards/ContentCard/ContentCardImage.stories.mdx
- stories/Components/UIcomponents/Cards/ContentCard/ContentCardWithOutImage.jsx
- stories/Components/UIcomponents/Cards/ContentCard/ContentCardWithOutImage.stories.mdx
- stories/Components/UIcomponents/Cards/ImageRevelCTACard/ImageCard.jsx
- stories/Components/UIcomponents/Cards/ImageRevelCTACard/ImageCard.stories.mdx
- stories/Molecules/Blocks/PublicationCard/publicationcard.scss
- stories/Organism/Blocks/ContentCardWithAndWithoutImage/ContentCardWithAndWithoutImage.stories.mdx
- stories/Organism/Blocks/ImageRevelCards/ImageRevelCards.stories.mdx
- stories/Templates/PublicationPage/PublicationPage.jsx
- stories/Templates/PublicationPage/PublicationPage.stories.mdx
- stories/Templates/PublicationPage/publicationpage.scss
- stories/assets/js/sticky.js
Issues resolved for UND-546 & UND-547
> UND-546/47 issues resolved

- stories/Components/Forms/expandable search/SearchExpand.scss
- stories/Components/Navigationcomponents/Breadcrumbs/breadcrumbs.scss
- stories/Templates/Articlepage/ArticlePage.scss
- stories/Templates/Authors/Authors.jsx
- stories/Templates/Authors/Authors.scss
- stories/Templates/Authors/Authors.stories.mdx
Article page, bread crumb issues fixed
> und-563, und-565

- stories/Components/UIcomponents/Cards/FeaturedCards/FeaturedContentCard.jsx
- stories/Components/UIcomponents/Cards/FeaturedCards/featuredContentCard.scss
- stories/Components/UIcomponents/Carousel/FixedSizeCarousel/FixedSizeCarousel.jsx
- stories/Components/UIcomponents/Carousel/FixedSizeCarousel/FixedSizeCarousel.stories.mdx
- stories/Components/UIcomponents/Carousel/FixedSizeCarousel/fixedsizecarousel.scss
- stories/Molecules/Blocks/TweetCard/TweetCard.stories.mdx
- stories/Molecules/Text/TextBackground/TextBackground.jsx
- stories/Molecules/Text/TextBackground/TextBackground.stories.mdx
- stories/Molecules/Text/TextBackground/textbackground.scss
- stories/Molecules/Text/TextCta/TextCta.jsx
- stories/Molecules/Text/TextCta/textcta.scss
- stories/Organism/Blocks/FeaturedContentCard/FeaturedCard/FeaturedCard.stories.mdx
- stories/Organism/Blocks/TweetPanel/TweetPanel.stories.mdx
- stories/Templates/GlobalHomepage/GlobalHomepage.jsx
- stories/Templates/GlobalHomepage/GlobalHomepage.stories.mdx
- stories/Templates/GlobalHomepage/globalhomepage.scss
Added global homepage template
> Created global home page

- stories/Molecules/FooterNavigation/FooterLogo/FooterLogo.jsx
- stories/Molecules/FooterNavigation/FooterLogo/FooterLogo.stories.mdx
- stories/Molecules/FooterNavigation/FooterLogo/footerLogo.scss
- stories/Organism/Footer/Footer.jsx
- stories/Organism/Footer/Footer.stories.mdx
- stories/Organism/Footer/FooterTwo.jsx
> update html for footer

- stories/Molecules/SDG/sdg.scss
Fixe mobile spacing and ipad color issue.
> fixed mobile spacing and tag colot issue

- stories/Molecules/Blocks/PublicationCard/PublicationCard.jsx
- stories/Molecules/Blocks/PublicationCard/publicationcard.scss
- stories/Templates/PublicationPage/PublicationPage.jsx
- stories/Templates/PublicationPage/PublicationPage.stories.mdx
- stories/Templates/PublicationPage/publicationpage.scss
> UND-567 spacing Issue

- stories/Components/UIcomponents/Cards/BioCard/BioCard.stories.mdx
- stories/Components/UIcomponents/Cards/FeaturedCards/FeaturedContentCard.jsx
- stories/Components/UIcomponents/Cards/FeaturedCards/FeaturedContentCard.stories.mdx
- stories/Organism/Blocks/FeaturedContentCard/FeaturedCard/FeaturedCard.jsx
- stories/Organism/Blocks/FeaturedContentCard/FeaturedCard/FeaturedCard.stories.mdx
- stories/Organism/Blocks/FeaturedContentCard/FeaturedCard/featuredcard.scss
> default size select

- stories/Molecules/Imagecaption/Imagecaption.jsx
class removed on controls change
> class removed on controls change

- stories/Components/UIcomponents/Cards/FeaturedCards/featuredContentCard.scss
> spacing-issue

- stories/Atom/Images/Authorimage/authorimage.scss
- stories/Components/UIcomponents/Author/Authorcard/Authorcard.jsx
- stories/Components/UIcomponents/Author/Authorcard/Authorcard.stories.mdx
- stories/Components/UIcomponents/Author/Authorcolumn/Authors.jsx
- stories/Components/UIcomponents/Author/Authorcolumn/Authors.stories.mdx
- stories/Components/UIcomponents/Author/Authorcolumn/authors.scss
- stories/Molecules/SDG/sdg.scss
- stories/Templates/Articlepage/ArticlePage.jsx
- stories/Templates/Articlepage/ArticlePage.stories.mdx
add authors control and fixed spacing issues
> add authors control and fixed spacing issues

- stories/Components/Forms/expandable search/SearchExpand.stories.mdx
- stories/Molecules/Text/BlockquoteComponent/BlockquoteComponent.jsx
- stories/Molecules/Text/BlockquoteComponent/BlockquoteComponent.stories.mdx
- stories/Molecules/Text/BlockquoteComponent/blockquotecomp.scss
- stories/assets/scss/style.scss
> feedback issue

- stories/Molecules/DownloadRow/downloadrow.scss
> Fixed the issues

- stories/Atom/Cards/Card-thumbnail/card-thumbnail.scss
- stories/Components/UIcomponents/Cards/ContentCard/contentcard.scss
Content card spacing issue fixed
> Content Card Spacing Issues

- stories/Components/UIcomponents/Accordion/accordion.scss
> accordion-issue

- stories/Components/Forms/Dropdowns/Multiselect/multiselect.scss
- stories/assets/scss/_mixins.scss
> Dropdown Issues Fixed

- stories/assets/scss/_typography.scss
> Lists Spacing Issues

- stories/Components/UIcomponents/Cards/BioCard/biocard.scss
- stories/Components/UIcomponents/Cards/ContentCard/contentcard.scss
> hover-issue

- stories/Components/UIcomponents/Carousel/FixedSizeCarousel/FixedSizeCarousel.jsx
- stories/Components/UIcomponents/Carousel/FixedSizeCarousel/fixedsizecarousel.scss
- stories/Components/UIcomponents/Carousel/FluidImageSizeCarousel/FluidImageSizeCarousel.jsx
- stories/Components/UIcomponents/Carousel/FluidImageSizeCarousel/fluidimagesizecarousel.scss
- stories/Components/UIcomponents/Carousel/ImageOnlyCarousel/ImageOnlyCarousel.jsx
- stories/Components/UIcomponents/Carousel/ImageOnlyCarousel/imageonlycarousel.scss
fixed spaceing and pagenation issue in carousels
> fixed spaceing and pagenation issue in carousels

- stories/Components/UIcomponents/Modal/modal.scss
- stories/Patterns/DownloadModal/DownloadModal.jsx
- stories/Patterns/DownloadModal/DownloadModal.stories.mdx
- stories/Patterns/DownloadModal/downloadmodal.scss
> Download Modal Issues Fixed

- stories/Components/Forms/Newslettersignup/signup.scss
- stories/Molecules/FooterNavigation/FooterLists/footerLists.scss
- stories/Organism/Footer/footer.scss
> footer-issue

- stories/Components/UIcomponents/Gallery/ParallaxGallery/ParallaxGallery.jsx
- stories/Components/UIcomponents/Gallery/ParallaxGallery/ParallaxGallery.stories.mdx
- stories/Components/UIcomponents/Gallery/ParallaxGallery/parallaxgallery.scss
- stories/assets/js/parallax-gallery.js
fixed gallery spacing issue and change control names
> fixed gallery spacing issue and change control names

- stories/Organism/Footer/footer.scss
> footer 2 spacing

- stories/Components/Forms/Checkbox/Checkbox.jsx
- stories/Components/Forms/Radio/Radio.jsx
- stories/Patterns/DownloadModal/DownloadModal.jsx
- stories/assets/js/downloadmodal.js
Remove class in the checkbox, radio, and some changes in download modal js.
> Checkbox Radio remove classes

- stories/Atom/Images/Authorimage/Authorimages.jsx
- stories/Atom/Images/Authorimage/Authorimages.stories.mdx
- stories/Components/Forms/Dropdowns/CustomSelect/customselect.scss
- stories/Components/Forms/Dropdowns/Multiselect/multiselect.scss
- stories/Components/UIcomponents/Author/Authorcard/Authorcard.jsx
- stories/Components/UIcomponents/Author/Authorcard/Authorcard.stories.mdx
- stories/Components/UIcomponents/Author/Authorcolumn/Authors.jsx
- stories/Components/UIcomponents/Author/Authorcolumn/Authors.stories.mdx
- stories/Molecules/Blocks/StatsPanel/StatsPanel.jsx
- stories/Molecules/Blocks/StatsPanel/StatsPanel.stories.mdx
- stories/Molecules/Blocks/StatsPanel/statspanel.scss
- stories/assets/scss/_mixins.scss
- stories/assets/scss/_variables.scss
Add modifiers in the stats panel.
> Stats Panel Add Modifiers

- stories/Components/UIcomponents/Cards/FeaturedCards/FeaturedContentCard.jsx
- stories/Organism/Blocks/FeaturedContentCard/FeaturedCard/featuredcard.scss
update featured-card for tablet.
> update featured-card for tablet

- stories/Molecules/Blocks/StatsPanel/StatsPanel.jsx
- stories/Molecules/Blocks/StatsPanel/statspanel.scss
- stories/Organism/Stats/Stats.jsx
Stats panel fixed class and css
> Stats Panel fixed class

- stories/Organism/Blocks/FeaturedContentCard/PagewideContentCard/PageWideCard.jsx
- stories/Organism/Blocks/FeaturedContentCard/PagewideContentCard/PageWideCard.stories.mdx
- stories/Organism/Blocks/FeaturedContentCard/PagewideContentCard/pagewidecard.scss
- stories/assets/js/cardgradient.js
> Update html for pagewide card

- stories/Components/UIcomponents/Cards/ContentCard/contentcard.scss
- stories/Organism/Blocks/FeaturedContentCard/PagewideContentCard/pagewidecard.scss
> card spacing issue

- stories/Templates/GenericPage/GenericPage.jsx
- stories/Templates/GenericPage/GenericPage.stories.mdx
- stories/Templates/GenericPage/genericpage.scss
- stories/Templates/LandingPage/GenericLandingPage.jsx
- stories/Templates/LandingPage/GenericLandingPage.stories.mdx
- stories/Templates/LandingPage/genericlandingpage.scss
- stories/Templates/PublicationPage/publicationpage.scss
UND 533 issues resolved, Global header added
> UND-533 Issues Resolved

- stories/Components/UIcomponents/Cards/StatsCards/StatsCards.jsx
> changed div to tag

- stories/Components/Forms/Dropdowns/Multiselect/multiselect.scss
- stories/Components/UIcomponents/Author/Authorcard/Authorcard.jsx
- stories/Components/UIcomponents/Author/Authorcard/authorcard.scss
- stories/Components/UIcomponents/Author/Authorcolumn/Authors.jsx
- stories/Components/UIcomponents/Author/Authorcolumn/authors.scss
- stories/Organism/Blocks/Authorcard/AuthorSummary.jsx
- stories/Organism/Blocks/Authorcard/authorsummary.scss
- stories/assets/scss/_mixins.scss
> Author Card Fixed

- stories/Components/UIcomponents/Buttons/Chips/chips.scss
- stories/Components/UIcomponents/Cards/FeaturedCards/FeaturedContentCard.jsx
- stories/Components/UIcomponents/Hero/Homepagehero/HomepageHero.jsx
- stories/Components/UIcomponents/Hero/Homepagehero/HomepageHero.stories.mdx
- stories/Components/UIcomponents/Hero/Homepagehero/HomepageHeroOption.jsx
- stories/Components/UIcomponents/Hero/Homepagehero/HomepageHeroSplit.jsx
- stories/Components/UIcomponents/Hero/Homepagehero/homepagehero.scss
- stories/Components/UIcomponents/Hero/Pageherocards/CountryCardHero.jsx
- stories/Components/UIcomponents/Hero/Pageherocards/countrycardhero.scss
- stories/Templates/GlobalHomepage/GlobalHomepage.stories.mdx
update html and spacing for homepage hero
> update html for homepage hero

- stories/Atom/Cards/Card-thumbnail/CardThumbnail.jsx
- stories/Atom/Cards/Card-thumbnail/CardThumbnail.stories.mdx
- stories/Atom/Cards/Card-thumbnail/card-thumbnail.scss
added controller for thumbnail card
> added controller for thumbnail card

- stories/Atom/Navigation/ProgressBarNavigation/ProgressBarNavigation.scss
- stories/Atom/Navigation/Sidebar-second-level/sidebarsecondlevel.scss
- stories/Components/Navigationcomponents/Breadcrumbs/Breadcrumbs.jsx
- stories/Components/Navigationcomponents/Breadcrumbs/breadcrumbs.scss
- stories/Components/Navigationcomponents/Menu/Menu.jsx
- stories/Components/Navigationcomponents/Menu/menu.scss
- stories/Components/UIcomponents/Gallery/ParallaxGallery/parallaxgallery.scss
- stories/Molecules/Sidebar-data/sidebardata.scss
> fixed Navigation bug

- stories/Components/UIcomponents/Cards/ImageRevelCTACard/imagecard.scss
- stories/Utilities/FrostedImage/frostedimage.scss
> Fixed blur and tranistion

- stories/Molecules/Blocks/PublicationCard/publicationcard.scss
- stories/Templates/PublicationPage/PublicationPage.jsx
- stories/Templates/PublicationPage/publicationpage.scss
- stories/assets/js/global-variables.js
- stories/assets/js/sticky.js
- stories/assets/scss/_variables.scss
publication card implementation issues updated in new branch
> Publication Card implementation issue

- stories/Components/UIcomponents/Cards/ContentCard/contentcard.scss
- stories/Components/UIcomponents/Cards/FeaturedCards/featuredContentCard.scss
- stories/Organism/Blocks/FeaturedContentCard/FeaturedCard/featuredcard.scss
> fixed testing card issue

- stories/Components/Forms/Inputfields/input_group.scss
- stories/Components/UIcomponents/Buttons/Cta_button/CtaButton.jsx
- stories/Components/UIcomponents/Buttons/Cta_link/cta_link.scss
> Fixed button and input issue

- stories/Components/UIcomponents/Carousel/FixedSizeCarousel/fixedsizecarousel.scss
- stories/Components/UIcomponents/Carousel/FluidImageSizeCarousel/fluidimagesizecarousel.scss
- stories/Components/UIcomponents/Carousel/ImageOnlyCarousel/imageonlycarousel.scss
- stories/assets/scss/_mixins.scss
> Fixed Pagination issue

- stories/Components/Navigationcomponents/Mainnavigation/MegaMenu/MegaMenu.stories.mdx
- stories/Components/Navigationcomponents/Mainnavigation/MobileNav/MobileNav.stories.mdx
> Und 54 55 new

- stories/Molecules/Blocks/PublicationCard/publicationcard.scss
- stories/Templates/PublicationPage/publicationpage.scss
- stories/assets/js/sticky.js
Here I did changes in publication page. All UI issues resolved. Please merge this branch
> Publication page issues

- .gitignore
- LICENSE
- README.md
- Added MIT License file
- Adde more text in Readme file
- A line in .gitignore file
> UNDP-622 Code license and Readme

- stories/Components/UIcomponents/Cards/FeaturedCards/featuredContentCard.scss
- stories/Organism/Blocks/FeaturedContentCard/FeaturedCard/featuredcard.scss
update featured card for  tablet
> update featured card for  tablet

- stories/Components/UIcomponents/Buttons/Chips/chips.jsx
- stories/Components/UIcomponents/Buttons/Chips/chips.stories.mdx
- stories/Components/UIcomponents/Buttons/Cta_button/CtaButton.jsx
- stories/Components/UIcomponents/Buttons/Cta_button/CtaButton.stories.mdx
- stories/Components/UIcomponents/Buttons/Cta_link/Cta_link.stories.mdx
- stories/Organism/Blocks/ContentCardWithAndWithoutImage/ContentCardWithAndWithoutImage.jsx
- stories/Patterns/DownloadModal/DownloadModal.jsx
- stories/Patterns/FilterAndSearchBar/FilterAndSearchBar.jsx
> Blur issue

- stories/Components/Navigationcomponents/Pagination/pagination.scss
- stories/Components/UIcomponents/Tab/Tab.jsx
- stories/Components/UIcomponents/Tab/tab.scss
Tabs and Pagination accessibility issue resolved.
> Tabs and Pagination accessibility

- stories/Components/Forms/Newslettersignup/SignUp.jsx
[UND-474][bug/UND-474-Sign-Up-Form]: UAT feedback bug.
> sign-up form feedback bug

- stories/Components/Navigationcomponents/Mainnavigation/GlobalHeader/GlobalHeader.scss
- stories/Templates/Authors/Authors.jsx
- stories/Templates/Authors/Authors.scss
- stories/Templates/Authors/Authors.stories.mdx
- stories/assets/scss/_typography.scss
Related to UND-542 issues on ready for QA
> Und 542 new

- stories/Atom/Navigation/ProgressBarNavigation/ProgressBarNavigation.jsx
- stories/Atom/Navigation/ProgressBarNavigation/ProgressBarNavigation.scss
- stories/Atom/Navigation/ProgressBarNavigation/ProgressBarNavigation.stories.mdx
- stories/Components/Forms/Inputfields/Input_group.jsx
- stories/Components/Forms/Inputfields/input_group.scss
- stories/Components/Forms/Inputfields/input_group.stories.mdx
- stories/Components/Forms/Textarea/Textarea.jsx
Fixed Progress and Input class issue
> Fixed Progress and Input class issue

- stories/Atom/Cards/Card-thumbnail/card-thumbnail.scss
- stories/Atom/Reach-element/Details/details.scss
- stories/Components/Navigationcomponents/Pagination/pagination.scss
- stories/Components/UIcomponents/Languageswitcher/languageswitcher.scss
UI issues in the storybook - card thumbnail, details, language switcher.
> UI issues inn storybook 

- .storybook/preview-head.html
- stories/Components/Navigationcomponents/Pagination/pagination.scss
- stories/Templates/GenericPage/genericpage.scss
Global header issue on all templates and generic template progress bar
> Global header issue

- stories/Atom/Label/Label.jsx
- stories/Atom/Label/Label.stories.mdx
- stories/Components/Forms/Inputfields/Input_group.jsx
- stories/Components/Forms/Inputfields/input_group.scss
- stories/Components/Forms/Inputfields/input_group.stories.mdx
- stories/Components/Forms/Textarea/Textarea.jsx
- stories/Components/UIcomponents/Buttons/Cta_link/cta_link.scss
- stories/Components/UIcomponents/Cards/FeaturedCards/FeaturedContentCard.jsx
- stories/Components/UIcomponents/Cards/FeaturedCards/featuredContentCard.scss
- stories/Organism/Blocks/FeaturedContentCard/FeaturedCard/featuredcard.scss
Fixed transition and label issue.
> Fixed transition and label issue

- stories/Components/Navigationcomponents/Mainnavigation/GlobalHeader/GlobalHeader.scss
- stories/Components/Navigationcomponents/Mainnavigation/MegaMenu/MegaMenu.jsx
- stories/Components/Navigationcomponents/Mainnavigation/MegaMenu/MegaMenu.scss
- stories/Components/Navigationcomponents/Mainnavigation/MobileNav/MobileNav.scss
- stories/Components/UIcomponents/Languageswitcher/languageswitcher.scss
- stories/assets/js/navigationData.js
- stories/assets/js/navigationData.json
> header issues fixed

- stories/Components/UIcomponents/Tab/tab.scss
- stories/assets/scss/_typography.scss
> mobile issue two tab selected

- stories/Components/UIcomponents/Cards/ImageRevelCTACard/imagecard.scss
> Fixed transition effect

- stories/Components/Forms/expandable search/SearchExpand.jsx
- stories/Components/Forms/expandable search/SearchExpand.scss
- stories/Templates/Authors/Authors.jsx
- stories/Templates/Authors/Authors.scss
- stories/assets/js/expand-search.js
> UND-733-Authors-page-issues-fixed

- stories/Components/Navigationcomponents/Menu/menu.scss
- stories/Components/UIcomponents/Cards/FeaturedCards/featuredContentCard.scss
- stories/Components/UIcomponents/Cards/ParallaxCard/ParallaxCards.jsx
- stories/Components/UIcomponents/Cards/ParallaxCard/parallaxcards.scss
- stories/Components/UIcomponents/Hero/Homepagehero/homepagehero.scss
- stories/Molecules/Text/TextCta/TextCta.jsx
- stories/Molecules/Text/TextCta/textcta.scss
- stories/Templates/GlobalHomepage/GlobalHomepage.jsx
- stories/Templates/GlobalHomepage/GlobalHomepage.stories.mdx
- stories/Templates/GlobalHomepage/globalhomepage.scss
- stories/assets/js/parallax.js
[UNDP-596][DEVELOP]: Added spacing for Global home page.
> added spacing for global page

- stories/Components/UIcomponents/Hero/Pageherocards/CountryCardHero.jsx
- stories/Components/UIcomponents/Hero/Pageherocards/countrycardhero.scss
> und-598-made changes as required

- stories/Patterns/DownloadModal/DownloadModal.jsx
Download Modal add aria-modal=true, 'role' as 'dialog, and some changes.
> [UNDP-627][DEVELOP]: Download Modal Feedback.

- .storybook/preview-head.html
- stories/Components/Navigationcomponents/Mainnavigation/CountrySiteHeader/CountrySiteHeader.stories.mdx
- stories/Components/Navigationcomponents/Mainnavigation/GlobalHeader/GlobalHeader.stories.mdx
- stories/Molecules/Sdgmodal/sdgmodal.scss
- stories/Organism/Footer/Footer.stories.mdx
- stories/Organism/Text/ProjectDetail/ProjectDetail.jsx
- stories/Organism/Text/ProjectDetail/projectdetail.scss
- stories/Templates/Articlepage/ArticlePage.stories.mdx
- stories/Templates/AuthorPage/AuthorPage.stories.mdx
- stories/Templates/Authors/Authors.stories.mdx
- stories/Templates/CountryHomepage/CountryHomepage.stories.mdx
- stories/Templates/GenericPage/GenericPage.stories.mdx
- stories/Templates/GlobalHomepage/GlobalHomepage.stories.mdx
- stories/Templates/LandingPage/GenericLandingPage.stories.mdx
- stories/Templates/PublicationPage/PublicationPage.stories.mdx
- stories/Templates/SDG/Sdg.jsx
- stories/Templates/SDG/Sdg.stories.mdx
- stories/Templates/SDG/sdg.scss
Spacing is missing in the storybook and fixed project details on mobile UI.
> [UNDP-739][DEVELOP]: Spacing is missing in storybook.

- stories/Components/UIcomponents/Cards/StatsCards/StatsCards.jsx
- stories/Molecules/Blocks/StatsPanel/StatsPanel.jsx
- stories/Molecules/Blocks/StatsPanel/statspanel.scss
Used stats card component in stats panel
> Used stats card component in stats panel

- stories/Atom/Table/table.jsx
- stories/Utilities/Progressbar/progress_bar.jsx
Reach Elements Dev Code Feedback spacing issue in classes, structure when switching the controls.
> Reach Elements Dev Code Feedback

- stories/Components/Forms/Checkbox/Checkbox.jsx
- stories/Components/Forms/Radio/Radio.jsx
- stories/Molecules/DownloadRow/DownloadRow.jsx
- stories/Molecules/DownloadRow/DownloadRow.stories.mdx
- stories/Molecules/DownloadRow/downloadrow.scss
- stories/Patterns/DownloadModal/downloadmodal.scss
- stories/assets/js/downloadmodal.js
[UNDP-628][DEVELOP]: Added aria attribute for form molecule
> update form molecule structure

- stories/Molecules/Blocks/StatsPanel/StatsPanel.jsx
- stories/Molecules/Blocks/StatsPanel/StatsPanel.stories.mdx
- stories/Organism/Stats/Stats.jsx
Stats panel remove some extra class and div.
> [UNDP-631][DEVELOP]: Stats panel feedback.

- stories/Atom/Cards/Card-thumbnail/card-thumbnail.scss
- stories/Atom/Cards/Publication-thumbnail/publication-thumbnail.scss
- stories/Components/UIcomponents/Cards/ContentCard/ContentCardImage.stories.mdx
- stories/Components/UIcomponents/Cards/ContentCard/ContentCardWithOutImage.stories.mdx
- stories/Components/UIcomponents/Cards/ContentCard/contentcard.scss
- stories/Components/UIcomponents/Cards/FeaturedCards/featuredContentCard.scss
- stories/Organism/Blocks/ContentCard/ContentCard.stories.mdx
- stories/Organism/Blocks/FeaturedContentCard/PagewideContentCard/pagewidecard.scss
Content card RTL hover color issues fixed
> und-638 content cards hover issues fixed

- stories/Components/Forms/Checkbox/Checkbox.jsx
- stories/Components/Forms/Checkbox/checkbox.scss
- stories/Components/Forms/Dropdowns/Multiselect/multiselect.scss
- stories/Components/Forms/Radio/Radio.jsx
- stories/Components/Forms/Radio/radio.scss
- stories/Molecules/DownloadRow/downloadrow.scss
- stories/Patterns/DownloadModal/DownloadModal.jsx
- stories/assets/js/downloadmodal.js
Checkbox and Radio code feedbacks.
> [UNDP-630][DEVELOP]: Checkbox and Radio Feedback.

- stories/Components/UIcomponents/Languageswitcher/Languageswitcher.jsx
- stories/Components/UIcomponents/Languageswitcher/Languageswitcher.stories.mdx
- stories/Components/UIcomponents/Languageswitcher/languageswitcher.scss
- stories/assets/js/Lang_switcher.js
[UNDP-624][DEVELOP]: Update language switcher html
> Update language switcher

- stories/Molecules/Blocks/PublicationCard/PublicationCard.jsx
- stories/Molecules/Blocks/PublicationCard/publicationcard.scss
- stories/Templates/PublicationPage/PublicationPage.stories.mdx
- stories/Templates/PublicationPage/publicationpage.scss
- stories/assets/scss/_variables.scss
[UND-731][bug/UND-731-Publication-Page-Card-Issue]: Publication page card issues resolved.
> Publication page card issue

- stories/Atom/Base-typography/Blockquote/blockquote.stories.mdx
- stories/Atom/Cards/Publication-thumbnail/PublicationThumbnail.jsx
- stories/Atom/Cards/Publication-thumbnail/PublicationThumbnail.stories.mdx
- stories/Atom/Cards/Publication-thumbnail/publication-thumbnail.scss
- stories/Atom/Navigation/ProgressBarNavigation/ProgressBarNavigation.jsx
- stories/Atom/Navigation/ProgressBarNavigation/ProgressBarNavigation.scss
- stories/Atom/Navigation/ProgressBarNavigation/ProgressBarNavigation.stories.mdx
- stories/Components/UIcomponents/Cards/ContentCard/contentcard.scss
- stories/Components/UIcomponents/Cards/StatsCards/StatsCards.jsx
- stories/Components/UIcomponents/Cards/StatsCards/StatsCards.stories.mdx
- stories/Components/UIcomponents/Cards/StatsCards/statscards.scss
- stories/Molecules/Blocks/DownloadCard/DownloadCard.jsx
- stories/Molecules/Blocks/PublicationCard/PublicationCard.jsx
- stories/Molecules/Text/BlockquoteComponent/BlockquoteComponent.jsx
- stories/Molecules/Text/BlockquoteComponent/BlockquoteComponent.stories.mdx
- stories/Patterns/DownloadModal/DownloadModal.jsx
- stories/Templates/Articlepage/ArticlePage.jsx
- stories/Templates/AuthorPage/AuthorPage.jsx
- stories/Templates/GenericPage/GenericPage.jsx
- stories/Templates/LandingPage/GenericLandingPage.jsx
Add controls for change modifier classes.
> [UNDP-160][DEVELOP]: Apply modifier for 4 allowed colors.

- stories/Atom/Base-typography/Hr/hr.jsx
- stories/assets/scss/_typography.scss
[UNDP-723][DEVELOP]: Update heading and hr of base typography
> update base typography

- stories/Molecules/Text/BlockCTA/BlockCTA.jsx
- stories/Molecules/Text/BlockCTA/blockCTA.scss
- stories/Molecules/Text/Page/Page.jsx
TextDev code feedback for text molecules option.
> TextDev code feedback

- stories/Components/UIcomponents/Author/Authorcard/Authorcard.jsx
- stories/Components/UIcomponents/Author/Authorcolumn/Authors.jsx
- stories/Components/UIcomponents/Author/Authorcolumn/authors.scss
> [UNDP-664][DEVELOP]: Add link in authors

- stories/Molecules/Blocks/DownloadCard/DownloadCard.scss
> UND-551 -download card issue fixed

- .stylelintrc.json
- stories/Atom/Cards/Card-thumbnail/card-thumbnail.scss
- stories/Atom/Cards/Publication-thumbnail/publication-thumbnail.scss
- stories/Atom/Table/table.scss
- stories/Components/Forms/Checkbox/Checkbox.jsx
- stories/Components/Forms/Newslettersignup/signup.scss
- stories/Components/Forms/Radio/Radio.jsx
- stories/Components/Navigationcomponents/Sidebar/Sidebar.jsx
- stories/Components/Navigationcomponents/Sidebar/sidebar.scss
- stories/Components/UIcomponents/Cards/ContentCard/contentcard.scss
- stories/Components/UIcomponents/Cards/FeaturedCards/featuredContentCard.scss
- stories/Components/UIcomponents/Languageswitcher/Languageswitcher.jsx
- stories/Molecules/Blocks/PublicationCard/PublicationCard.jsx
- stories/Molecules/Blocks/PublicationCard/publicationcard.scss
- stories/Molecules/Blocks/StatsPanel/StatsPanel.jsx
- stories/Organism/Blocks/FeaturedContentCard/PagewideContentCard/pagewidecard.scss
- stories/Organism/Stats/Stats.jsx
- stories/Patterns/DownloadModal/DownloadModal.jsx
- stories/Templates/PublicationPage/publicationpage.scss
- stories/assets/scss/_mixins.scss
issue - when we run the eslint command, it removes the prefix classes from the styling, so rules are defined for this in issue in stylelint file.
> UND-773 Font size is not consistent

- stories/Components/UIcomponents/Author/Authorcard/authorcard.scss
[UNDP-226][DEVELOP]: Update paragraph font size for author-card.
> update font size

- stories/Components/Navigationcomponents/Sidebar/Sidebar.jsx
- stories/Components/Navigationcomponents/Sidebar/sidebar.scss
- stories/Molecules/Sidebar-data/Sidebardata.jsx
- stories/Templates/GenericPage/GenericPage.jsx
- stories/Templates/GenericPage/GenericPage.stories.mdx
- stories/Templates/GenericPage/genericpage.scss
- stories/assets/js/Sidebar_custom.js
- stories/assets/scss/_mixins.scss
- stories/assets/scss/_variables.scss
[UND-740][bug/UND-740-Functional-Issue]: Generic page functional issues resolved
> Generic page functional issues

- stories/Atom/Images/Imagecaptioncredit/imagecaption.scss
- stories/Components/Forms/Inputfields/Input_group.jsx
- stories/Components/Forms/Inputfields/input_group.scss
- stories/Components/Forms/Newslettersignup/SignUp.jsx
- stories/Components/Forms/Newslettersignup/signup.scss
- stories/Components/Forms/Textarea/Textarea.jsx
- stories/Organism/Footer/Footer.jsx
- stories/Organism/Footer/footer.scss
> UND 558 Footer Dev code feedback

- stories/Components/UIcomponents/Cards/ContentCard/ContentCardWithOutImage.stories.mdx
- stories/Components/UIcomponents/Cards/ContentCard/contentcard.scss
[UND-441][DEVELOP]:UAT feedback single content-card image
> UAT feedback issues

- stories/Organism/Blocks/ContentCardWithAndWithoutImage/ContentCardWithAndWithoutImage.stories.mdx
- stories/Templates/CountryHomepage/CountryHomepage.stories.mdx
- stories/Templates/CountryHomepage/countryhomepage.scss
[UND-757][DEVELOP]-Country Homepage Footer Issue Resolved
> UND-757 footer issue

- stories/Atom/Navigation/Menu-items/Menu-Items.scss
- stories/Components/Navigationcomponents/Menu/Menu.jsx
- stories/assets/js/navigation.js
[UNDP-629][DEVELOP]: Update menu structure.
> Update menu html

- stories/Components/Navigationcomponents/Mainnavigation/MegaMenu/MegaMenu.scss
- stories/Components/UIcomponents/Hero/Pagehero/pagehero.scss
- stories/Molecules/SDG/sdg.scss
- stories/Molecules/Sdgmodal/Sdgmodal.jsx
- stories/Molecules/Sdgmodal/Sdgmodal.stories.mdx
- stories/Molecules/Sdgmodal/sdgmodal.scss
- stories/Organism/Statscardslider/Statscardslider.jsx
- stories/Organism/Statscardslider/statscardslider.scss
- stories/Templates/SDG/Sdg.jsx
- stories/Templates/SDG/Sdg.stories.mdx
- stories/Templates/SDG/sdg.scss
- stories/assets/js/sdgmodal.js
> [UNDP-766][DEVELOP]: SDG Functional Issues

- stories/Components/Navigationcomponents/Mainnavigation/MobileNav/MobileNav.scss
- stories/Components/UIcomponents/Hero/Pageherocards/countrycardhero.scss
- stories/Components/UIcomponents/Languageswitcher/Languageswitcher.stories.mdx
> Und 722 new

- stories/Atom/Table/table.scss
- stories/Atom/Table/table.stories.mdx
Removed nowrap from scroll table body cell
> Removed nowrap from scroll table body cell

- stories/Components/Forms/Dropdowns/CustomSelect/customselect.scss
- stories/Components/Forms/Inputfields/input_group.scss
- stories/Components/Navigationcomponents/Sidebar/sidebar.scss
- stories/Components/UIcomponents/Accordion/Accordion.jsx
- stories/Components/UIcomponents/Accordion/accordion.scss
- stories/Components/UIcomponents/Cards/FeaturedCards/featuredContentCard.scss
- stories/assets/js/Faq_custom.js
- stories/assets/scss/_mixins.scss
[UNDP-609][DEVELOP]: Added white background on some components.
> Addded white background

- stories/Templates/CountryHomepage/CountryHomepage.jsx
- stories/Templates/CountryHomepage/countryhomepage.scss
[UND-761][DEVELOP]-Country Homepage Font-size and alignment Issue
> Country Homepage Font-size and alignment Issue

- stories/Organism/Blocks/TweetPanel/tweetpanel.scss
- stories/Templates/GlobalHomepage/GlobalHomepage.jsx
- stories/assets/scss/_typography.scss
[UNDP-775][DEVELOP]: Added space for publication component for rtl.
> added space for publication

- stories/Templates/LandingPage/GenericLandingPage.jsx
- stories/Templates/LandingPage/GenericLandingPage.stories.mdx
- stories/Templates/LandingPage/genericlandingpage.scss
[UND-778][DEVELOP]-Generic Landing page implemtation issue resolved
> UND-778 Implementation Issue

- stories/Components/UIcomponents/Carousel/FixedSizeCarousel/fixedsizecarousel.scss
- stories/Components/UIcomponents/Carousel/FluidImageSizeCarousel/FluidImageSizeCarousel.jsx
- stories/Components/UIcomponents/Carousel/FluidImageSizeCarousel/fluidimagesizecarousel.scss
- stories/Components/UIcomponents/Carousel/ImageOnlyCarousel/ImageOnlyCarousel.jsx
- stories/Components/UIcomponents/Carousel/ImageOnlyCarousel/imageonlycarousel.scss
- stories/assets/scss/_mixins.scss
Fixed image height and arrows in rtl
> Fixed image height and arrows in rtl

- stories/Components/Forms/Inputfields/input_group.scss
- stories/Components/Forms/Newslettersignup/signup.scss
- stories/Organism/Footer/footer.scss
> email filed issue

- stories/Components/UIcomponents/Gallery/ParallaxGallery/parallaxgallery.scss
- stories/Molecules/Blocks/StatsPanel/statspanel.scss
- stories/assets/scss/_variables.scss
Fixed hover effect on stats panel
> Fixed hover effect on stats panel

- stories/Atom/Images/Imagecaptioncredit/Imagecaption.jsx
- stories/Atom/Images/Imagecaptioncredit/Imagecaption.stories.mdx
- stories/Atom/Images/Imagecaptioncredit/imagecaption.scss
- stories/Components/UIcomponents/Cards/ImageRevelCTACard/imagecard.scss
- stories/Molecules/Imagecaption/Imagecaption.jsx
- stories/Molecules/Imagecaption/Imagecaption.stories.mdx
Fig-caption added inside Figure tag
> Fig-cation added inside Figure tag

- stories/Components/Navigationcomponents/Mainnavigation/MegaMenu/MegaMenu.jsx
- stories/assets/js/navigation.js
- stories/assets/js/navigationData.js
> UND-711 dev code feedback

- stories/Components/UIcomponents/Cards/BioCard/biocard.scss
- stories/Components/UIcomponents/Cards/FeaturedCards/FeaturedContentCard.jsx
- stories/Components/UIcomponents/Cards/FeaturedCards/FeaturedContentCard.stories.mdx
- stories/Components/UIcomponents/Cards/FeaturedCards/featuredContentCard.scss
- stories/Components/UIcomponents/Cards/StatsCards/statscards.scss
- stories/Molecules/Blocks/StatsPanel/statspanel.scss
- stories/Molecules/Text/BlockquoteComponent/BlockquoteComponent.jsx
- stories/Molecules/Text/BlockquoteComponent/blockquotecomp.scss
- stories/Organism/Blocks/FeaturedContentCard/PagewideContentCard/PageWideCard.jsx
- stories/Organism/Blocks/FeaturedContentCard/PagewideContentCard/PageWideCard.stories.mdx
- stories/Organism/Blocks/FeaturedContentCard/PagewideContentCard/pagewidecard.scss
Add support -WebKit rules in stats card.
> [UNDP-641][DEVELOP]: Stats Card Issue

- stories/Components/UIcomponents/Carousel/FixedSizeCarousel/FixedSizeCarousel.jsx
- stories/Components/UIcomponents/Carousel/FluidImageSizeCarousel/FluidImageSizeCarousel.jsx
- stories/Components/UIcomponents/Carousel/ImageOnlyCarousel/ImageOnlyCarousel.jsx
- stories/Molecules/Sdgmodal/Sdgmodal.stories.mdx
- stories/Molecules/Sdgmodal/sdgmodal.scss
- stories/Organism/Blocks/ContentCardWithAndWithoutImage/contentcardwithandwithoutimage.scss
- stories/Organism/Statscardslider/Statscardslider.jsx
- stories/Templates/SDG/Sdg.stories.mdx
- stories/assets/js/Carousel.js
> [UNDP-770][DEVELOP]: SDG Compared Issue

- stories/assets/scss/_mixins.scss
- stories/assets/scss/_typography.scss
> Und-750 select

- stories/Components/Navigationcomponents/Mainnavigation/MobileNav/MobileNav.scss
- stories/assets/js/navigation.js
- stories/assets/js/navigationData.js
> und-746 mobile menu changes

- stories/Components/Forms/Dropdowns/CustomSelect/CustomSelect.jsx
- stories/Components/Forms/Dropdowns/CustomSelect/customselect.scss
und-748 UAT Feedback - (P0) - Forms | Atoms | Select
> und-748 UAT Feedback - (P0) - Forms | Atoms | Select

- stories/Components/Navigationcomponents/Mainnavigation/GlobalHeader/GlobalHeader.jsx
- stories/Components/Navigationcomponents/Mainnavigation/GlobalHeader/GlobalHeader.scss
- stories/Components/Navigationcomponents/Mainnavigation/MegaMenu/MegaMenu.scss
- stories/assets/scss/_mixins.scss
- stories/assets/scss/_variables.scss
UND-759 Navigation, Desktop Mega Menu
> UND-759 Navigation, Desktop Mega Menu

- stories/Components/Forms/Dropdowns/Multiselect/MultiSelect.jsx
- stories/Components/Forms/Dropdowns/Multiselect/MultiSelect.stories.mdx
- stories/Components/Forms/Dropdowns/Multiselect/multiselect.scss
- stories/Components/Forms/Radio/Radio.jsx
- stories/Components/Forms/Radio/Radio.stories.mdx
- stories/assets/scss/_mixins.scss
> und-749 select changes

- stories/Components/UIcomponents/Languageswitcher/Languageswitcher.jsx
- stories/Components/UIcomponents/Languageswitcher/languageswitcher.scss
- stories/assets/js/Lang_switcher.js
> UI Issues in storybook

- stories/Templates/PublicationPage/publicationpage.scss
[UND-717][DEVELOP]-Menu Uppercase issue
> Menu Uppercase issue

- stories/Molecules/Text/HeadingBig/HeadingBig.jsx
- stories/Molecules/Text/HeadingBig/HeadingBig.stories.mdx
- stories/Molecules/Text/HeadingBig/headingbig.scss
- stories/Templates/GenericPage/genericpage.scss
- stories/assets/js/smoothbgchange.js
[UND-760][DEVELOP]- Country Homepage Transition Issue
> UND-760 Animation-issue

- stories/Templates/AuthorPage/AuthorPage.jsx
- stories/Templates/AuthorPage/AuthorPage.scss
- stories/Templates/AuthorPage/AuthorPage.stories.mdx
> UND-783 author page changes

- stories/Molecules/DownloadRow/DownloadRow.jsx
- stories/Molecules/DownloadRow/DownloadRow.stories.mdx
[UNDP-552][DEVELOP]: removed data lang attribute from download row component.
> Removed data lang attribute

- stories/Organism/Blocks/Authorcard/AuthorSummary.jsx
[UNDP-226][DEVELOP]: Removed author card wrapper from author summary component.
> Removed author card wrapper

- stories/Atom/Images/Authorimage/Authorimages.jsx
- stories/Atom/Navigation/ProgressBarNavigation/ProgressBarNavigation.jsx
- stories/Components/Navigationcomponents/Breadcrumbs/Breadcrumbs.jsx
- stories/Components/UIcomponents/Cards/ParallaxCard/ParallaxCards.jsx
- stories/Components/UIcomponents/Cards/ParallaxCard/ParallaxCards.stories.mdx
- stories/Components/UIcomponents/Cards/ParallaxCard/parallaxcards.scss
- stories/Components/UIcomponents/Gallery/ParallaxGallery/ParallaxGallery.jsx
- stories/Components/UIcomponents/Gallery/ParallaxGallery/ParallaxGallery.stories.mdx
- stories/Molecules/ParallaxCard/ParallaxCard.jsx
- stories/Molecules/ParallaxCard/ParallaxCard.stories.mdx
- stories/Molecules/ParallaxCard/parallaxCard.scss
Add controls in parallax card and fixed organism level
> Add controls in parallax card and fixed organism lavel

- stories/Atom/Icons/arrow_left_white.jsx
- stories/Atom/Icons/arrow_right_white.jsx
- stories/Atom/Images/Image/Image.jsx
- stories/Atom/Layout/Grid/Grid.jsx
- stories/Components/UIcomponents/Cards/StatsCards/statscards.scss
- stories/Utilities/Loader/loader.jsx
[UND-626][DEVELOP]- Sonarqube bugs
> [bug/UND-626]-Sonarqube bugs

- stories/Components/Navigationcomponents/Breadcrumbs/Breadcrumbs.jsx
- stories/Components/Navigationcomponents/Breadcrumbs/breadcrumbs.scss
- stories/Components/Navigationcomponents/Menu/Menu.jsx
- stories/Components/Navigationcomponents/Menu/menu.scss
- stories/Components/Navigationcomponents/Pagination/Pagination.jsx
- stories/Components/Navigationcomponents/Pagination/pagination.scss
[UNDP-629][DEVELOP]: Update menu, pagination.
> Update menus, pagination

- stories/Templates/LandingPage/genericlandingpage.scss
[UND-793][DEVELOP] - Generic Landing Page Alignment Issue
> [UND-793][DEVELOP] - Alignment Issue

- stories/Atom/Base-typography/Abbr/abbr.stories.mdx
- stories/Atom/Base-typography/Blockquote/blockquote.stories.mdx
- stories/Atom/Base-typography/Cite/cite.stories.mdx
- stories/Atom/Base-typography/Code/code.stories.mdx
- stories/Atom/Base-typography/Hr/hr.stories.mdx
- stories/Atom/Base-typography/Mark/mark.stories.mdx
- stories/Atom/Base-typography/Paragraph/Paragarph.stories.mdx
- stories/Atom/Base-typography/Quotation/quotation.stories.mdx
- stories/Atom/Base-typography/Small/small.stories.mdx
- stories/Atom/Table/table.stories.mdx
> TOC update

- stories/Components/Navigationcomponents/Breadcrumbs/breadcrumbs.scss
- stories/Components/UIcomponents/Cards/BioCard/BioCard.jsx
- stories/Components/UIcomponents/Cards/BioCard/biocard.scss
- stories/Components/UIcomponents/Cards/FeaturedCards/FeaturedContentCard.jsx
[UNDP-328][DEVELOP]: Removed empty img tag from featured card component.
> Removed empty img tag

- stories/Components/Forms/Dropdowns/Multiselect/multiselect.scss
> und-815 multiselect rtl issue fixed

- stories/Components/Navigationcomponents/Mainnavigation/CountrySiteHeader/CountrySiteHeader.jsx
- stories/Components/Navigationcomponents/Mainnavigation/GlobalHeader/GlobalHeader.jsx
- stories/Components/Navigationcomponents/Mainnavigation/GlobalHeader/GlobalHeader.scss
- stories/Components/Navigationcomponents/Mainnavigation/MegaMenu/MegaMenu.scss
- stories/Components/Navigationcomponents/Mainnavigation/MobileNav/MobileNav.scss
- stories/assets/js/navigation_data.js
> und-801 header issue fixed

- stories/Atom/Cards/Card-thumbnail/card-thumbnail.scss
- stories/Atom/Cards/Publication-thumbnail/publication-thumbnail.scss
- stories/Molecules/Blocks/DownloadCard/DownloadCard.jsx
- stories/Molecules/Blocks/DownloadCard/DownloadCard.scss
- stories/Molecules/Blocks/DownloadCard/DownloadCard.stories.mdx
- stories/Templates/LandingPage/genericlandingpage.scss
[UND-519][DEVELOP]- Publication/Download Card issues
> Publication/Download Card

- stories/Atom/Images/Imagecaptioncredit/Imagecaption.jsx
- stories/Atom/Table/table.jsx
- stories/Components/Forms/Newslettersignup/SignUp.jsx
- stories/Components/UIcomponents/Accordion/Accordion.jsx
- stories/Components/UIcomponents/Cards/BioCard/BioCard.jsx
- stories/Components/UIcomponents/Languageswitcher/Languageswitcher.jsx
- stories/Molecules/FooterNavigation/FooterConditions/FooterConditions.jsx
- stories/Molecules/FooterNavigation/FooterConditions2/FooterConditions2.jsx
- stories/Molecules/FooterNavigation/FooterIcons/FooterIcons.jsx
- stories/Molecules/FooterNavigation/FooterLists/FooterLists.jsx
- stories/Molecules/FooterNavigation/FooterLogo/FooterLogo.jsx
- stories/Molecules/Imagecaption/Imagecaption.jsx
- stories/Organism/Footer/Footer.jsx
- stories/Organism/Footer/FooterTwo.jsx
> class attribute remove issue

- stories/Atom/Icons/Icons.stories.mdx
> Fixed Icons Path

- stories/Templates/ProjectPage/projectpage.scss
[UND-822][DEVELOP] - Project page header section
> [UND-822][DEVELOP] - Project page header section

- stories/Organism/Statscardslider/Statscardslider.jsx
- stories/Templates/GlobalHomepage/GlobalHomepage.jsx
- stories/Templates/ProjectPage/ProjectPage.jsx
- stories/Templates/ProjectPage/projectpage.scss
[UND-823][DEVELOP]-Project page card issue
> [UND-823][DEVELOP]-Project page card issue

- stories/Components/UIcomponents/Gallery/ParallaxGallery/ParallaxGallery.jsx
- stories/Components/UIcomponents/Gallery/ParallaxGallery/ParallaxGallery.stories.mdx
- stories/Components/UIcomponents/Gallery/ParallaxGallery/parallaxgallery.scss
Fixed the spelling of gray control
> Fixed the spelling of gray control

- stories/Components/Forms/Inputfields/Input_group.jsx
- stories/Components/Forms/Inputfields/input_group.scss
- stories/Components/Forms/Newslettersignup/SignUp.jsx
- stories/Components/Forms/Newslettersignup/signup.scss
- stories/Components/Forms/Textarea/Textarea.jsx
[UNDP-712][DEVELOP]: Removed class from input type
> Removed input type class

- stories/Utilities/FrostedImage/frostedimage.scss
[UNDP-227][DEVELOP]: Update frosted overlay effect.
> Update frosted effect

- stories/Atom/Icons/Icons.stories.mdx
- stories/Atom/Layout/Breakpoint/Breakpoint.stories.mdx
- stories/Atom/Layout/Grid/Grid.stories.mdx
- stories/Atom/Layout/Spacing/spacing.stories.mdx
- stories/Organism/Blocks/Authorcard/AuthorSummary.jsx
- stories/Patterns/DownloadModal/DownloadModal.jsx
- stories/Utilities/Scroll-bar/ScrollBar.jsx
Accessibility Violation Issue Fixed.
> [UNDP-491][DEVELOP]: Accessibility Violation Issue Fixed

- .storybook/preview.js
- stories/Atom/Table/table.scss
- stories/Components/Navigationcomponents/Mainnavigation/CountrySiteHeader/CountrySiteHeader.jsx
- stories/Components/Navigationcomponents/Mainnavigation/GlobalHeader/GlobalHeader.jsx
- stories/Components/Navigationcomponents/Menu/Menu.jsx
- stories/Components/Navigationcomponents/Menu/Menu.stories.mdx
- stories/Molecules/FooterNavigation/FooterConditions/footerCondition.scss
- stories/Molecules/FooterNavigation/FooterLists/footerLists.scss
- stories/Molecules/Sdgmodal/sdgmodal.scss
- stories/assets/js/sdgmodal.js
> [UNDP-800][DEVELOP]: SDG Issues Multiples

- stories/Components/UIcomponents/Cards/FeaturedCards/FeaturedContentCard.jsx
- stories/Components/UIcomponents/Cards/FeaturedCards/featuredContentCard.scss
- stories/Components/UIcomponents/Hero/Pageherocards/countrycardhero.scss
- stories/assets/scss/_mixins.scss
[UNDP-666][DEVELOP]: Update chevron for the featured card on tablet view and page hero card.
> update country card

- stories/Components/UIcomponents/Author/Authorcolumn/Authors.jsx
- stories/Components/UIcomponents/Author/Authorcolumn/authors.scss
In auhtors use <a> tags as cell containers.
> [UNDP-664][DEVELOP]: Feedbacks Author

- stories/Organism/Blocks/FeaturedContentCard/PagewideContentCard/PageWideCard.jsx
- stories/Organism/Blocks/FeaturedContentCard/PagewideContentCard/pagewidecard.scss
- stories/assets/js/cardgradient.js
[UNDP-471][DEVELOP]: Removed hover effect from read more button of pagewide card
> Removed hover effect

- stories/Components/Forms/Checkbox/Checkbox.jsx
- stories/Molecules/DownloadRow/DownloadRow.jsx
- stories/Molecules/DownloadRow/downloadrow.scss
[UNDP-552][DEVELOP]: Update download row.
> Update download row

- stories/Components/UIcomponents/Buttons/Chips/chips.jsx
- stories/Components/UIcomponents/Buttons/Cta_button/CtaButton.jsx
- stories/Components/UIcomponents/Buttons/Cta_link/Cta_link.jsx
> Removed active class

- .storybook/preview.js
- stories/Atom/Icons/Icons.stories.mdx
- stories/Atom/Icons/icons.scss
- stories/Components/Forms/Inputfields/input_group.scss
- stories/Components/Forms/Newslettersignup/SignUp.jsx
Newsletter Signup Issues Fixed.
> [UNDP-872][DEVELOP]: Newsletter Signup Issues Fixed

- stories/Utilities/FrostedImage/frostedimage.scss
[UNDP-227][DEVELOP]: Update frosted background
> Update frosted background

- stories/Components/UIcomponents/Accordion/Accordion.jsx
- stories/Components/UIcomponents/Accordion/Accordion.stories.mdx
- stories/Components/UIcomponents/Accordion/accordion.scss
- stories/Components/UIcomponents/Cards/ContentCard/contentcard.scss
- stories/Molecules/Blocks/PublicationCard/publicationcard.scss
- stories/assets/js/accordion.js
[UND-818][DEVELOP]- UI Breaking issue
> UND-818- UI Breaking issue

- stories/Components/Forms/Dropdowns/CustomSelect/CustomSelect.jsx
- stories/Components/Forms/Dropdowns/CustomSelect/customselect.scss
- stories/Components/Forms/Dropdowns/Multiselect/MultiSelect.jsx
- stories/Components/Forms/Dropdowns/Multiselect/MultiSelect.stories.mdx
- stories/Components/Forms/Dropdowns/Multiselect/multiselect.scss
- stories/Patterns/FilterAndSearchBar/FilterAndSearchBar.jsx
- stories/Patterns/FilterAndSearchBar/FilterAndSearchBar.scss
- stories/assets/js/filter_seach_bar.js
- stories/assets/js/multiselect.js
select feedback, clean up obsolete elements
> und-600 select uat feedback

- stories/Components/Forms/Inputfields/input_group.scss
- stories/Components/Forms/SearchBox/Searchbox.jsx
- stories/Components/Forms/SearchBox/Searchbox.stories.mdx
[UNDP-30][DEVELOP]: Added control for search box.
> Added control for search box

- stories/Components/UIcomponents/Gallery/ParallaxGallery/ParallaxGallery.jsx
- stories/Components/UIcomponents/Gallery/ParallaxGallery/parallaxgallery.scss
Fixed Parallax rtl image space issue
> Parallax rtl image space issue

- stories/Organism/Text/ProjectDetail/ProjectDetail.jsx
- stories/Organism/Text/ProjectDetail/projectdetail.scss
> [UNDP-32][DEVELOP]: Project Detail Issues

- stories/Molecules/Blocks/TweetCard/TweetCard.jsx
- stories/Molecules/Blocks/TweetCard/TweetCard.stories.mdx
- stories/Molecules/Blocks/TweetCard/tweetcard.scss
- stories/Organism/Blocks/TweetPanel/TweetPanel.jsx
- stories/Organism/Blocks/TweetPanel/TweetPanel.stories.mdx
- stories/Organism/Blocks/TweetPanel/tweetpanel.scss
[UNDP-369][DEVELOP]: update tweet panel structure.
> update tweet panel structure

- stories/Components/UIcomponents/Cards/StatsCards/StatsCards.jsx
- stories/Components/UIcomponents/Cards/StatsCards/statscards.scss
- stories/Molecules/Blocks/StatsPanel/statspanel.scss
- stories/Molecules/Sdgmodal/sdgmodal.scss
- stories/Organism/Stats/Stats.jsx
- stories/Organism/Statscardslider/Statscardslider.jsx
- stories/Patterns/StatsSlider/StatsSlider.jsx
- stories/Patterns/StatsSlider/statsslider.scss
- stories/assets/js/stats.js
Stats Panel and Card Issues Fixed.
> [UNDP-549][DEVELOP]: Stats Panel and Card Issues Fixed

- stories/Components/UIcomponents/Author/Authorcard/Authorcard.jsx
- stories/Components/UIcomponents/Author/Authorcard/authorcard.scss
- stories/Components/UIcomponents/Author/Authorcolumn/Authors.jsx
- stories/Components/UIcomponents/Author/Authorcolumn/authors.scss
> [UNDP-664][DEVELOP]: Author card feedbacks

- stories/Components/UIcomponents/Cards/ParallaxCard/ParallaxCards.jsx
- stories/Molecules/ParallaxCard/ParallaxCard.jsx
- stories/Molecules/ParallaxCard/ParallaxCard.stories.mdx
- stories/Molecules/ParallaxCard/parallaxCard.scss
> Changed parallax card classes

- stories/Atom/Icons/icons.scss
> [UNDP-884][DEVELOP]: Icons Mobile UI Fixed

- stories/Components/UIcomponents/Cards/ParallaxCard/ParallaxCards.jsx
- stories/Components/UIcomponents/Carousel/FixedSizeCarousel/FixedSizeCarousel.jsx
- stories/Components/UIcomponents/Carousel/FixedSizeCarousel/fixedsizecarousel.scss
- stories/Components/UIcomponents/Carousel/FluidImageSizeCarousel/FluidImageSizeCarousel.jsx
- stories/Components/UIcomponents/Carousel/FluidImageSizeCarousel/fluidimagesizecarousel.scss
- stories/Components/UIcomponents/Carousel/ImageOnlyCarousel/ImageOnlyCarousel.jsx
- stories/Components/UIcomponents/Carousel/ImageOnlyCarousel/imageonlycarousel.scss
- stories/Components/UIcomponents/Hero/Pageherocards/CountryCardHero.jsx
- stories/Molecules/Blocks/CountryCard/CountryCard.jsx
- stories/Patterns/StatsSlider/StatsSlider.jsx
- stories/assets/js/carousel.js
- stories/assets/scss/_base.scss
- stories/assets/scss/_glideslider.scss
> Carousels accessibility

- stories/Components/UIcomponents/Buttons/Cta_button/CtaButton.jsx
- stories/Components/UIcomponents/Cards/BioCard/BioCard.jsx
- stories/Components/UIcomponents/Cards/BioCard/biocard.scss
- stories/Components/UIcomponents/Modal/Modal.jsx
- stories/Components/UIcomponents/Modal/Modal.stories.mdx
- stories/Components/UIcomponents/Modal/modal.scss
- stories/Utilities/FrostedImage/frostedimage.scss
- stories/assets/js/modal.js
> UAT modal feedback

- stories/assets/js/lightbox-gallery.js
> UND-831-mobile-issue

- stories/Components/UIcomponents/Languageswitcher/languageswitcher.scss
[UNDP-842][DEVELOP]: Added spacing on rtl for language switcher.
> Added spacing for rtl

- stories/Atom/Typography/Heading/Heading.jsx
- stories/Components/Forms/Checkbox/Checkbox.jsx
- stories/Molecules/DownloadRow/DownloadRow.jsx
[UNDP-552][DEVELOP]: Added aria attribute for download row.
> Added aria attribute

- stories/Atom/Navigation/Menu-items/Menu-Items.jsx
- stories/Components/Navigationcomponents/Mainnavigation/CountrySiteHeader/CountrySiteHeader.jsx
- stories/Components/Navigationcomponents/Mainnavigation/GlobalHeader/GlobalHeader.jsx
- stories/Components/Navigationcomponents/Mainnavigation/GlobalHeader/GlobalHeader.scss
- stories/Components/Navigationcomponents/Mainnavigation/MegaMenu/MegaMenu.scss
- stories/Components/Navigationcomponents/Mainnavigation/MobileNav/MobileNav.jsx
- stories/Components/Navigationcomponents/Mainnavigation/MobileNav/MobileNav.scss
- stories/Components/Navigationcomponents/Menu/Menu.jsx
- stories/assets/js/navigation.js
> und-883 header cleanup

- stories/Molecules/Blocks/CountryCard/countrycard.scss
- stories/assets/scss/_variables.scss
> und-882 page hero feedbacks

- stories/Components/UIcomponents/Hero/Pageherocards/CountryCardHero.jsx
- stories/Components/UIcomponents/Hero/Pageherocards/countrycardhero.scss
- stories/Molecules/Blocks/CountryCard/CountryCard.jsx
- stories/Molecules/Blocks/CountryCard/countrycard.scss
- stories/assets/scss/_base.scss
> Country Card changes

- stories/Atom/Layout/Spacing/spacing.jsx
- stories/Atom/Layout/Spacing/spacing.scss
- stories/Atom/Layout/Spacing/spacing.stories.mdx
[UNDP-560][DEVELOP]: Update spacing component.
> Update spacing component

- stories/Components/Forms/Inputfields/Input_group.jsx
- stories/Components/Forms/Inputfields/input_group.stories.mdx
- stories/Components/Forms/SearchBox/Searchbox.jsx
- stories/Components/Forms/SearchBox/Searchbox.stories.mdx
- stories/Components/Forms/Textarea/Textarea.jsx
[UNDP-30[DEVELOP]: Added id on input type
> [UNDP-30[DEVELOP]: Added id on input type

- stories/Atom/Navigation/ProgressBarNavigation/ProgressBarNavigation.jsx
- stories/Atom/Navigation/ProgressBarNavigation/ProgressBarNavigation.scss
> progress bar class changes

- stories/Components/UIcomponents/Cards/ImageRevelCTACard/ImageCard.jsx
- stories/Components/UIcomponents/Cards/ImageRevelCTACard/imagecard.scss
[UNDP-714][DEVELOP]: update image reveal card
> update image reveal card

- stories/Components/UIcomponents/Cards/ContentCard/ContentCardImage.jsx
- stories/Components/UIcomponents/Cards/ContentCard/ContentCardWithOutImage.jsx
- stories/Components/UIcomponents/Cards/ContentCard/contentcard.scss
- stories/Molecules/Sdgmodal/sdgmodal.scss
- stories/Organism/Blocks/ContentCardWithAndWithoutImage/ContentCardWithAndWithoutImage.jsx
- stories/Organism/Blocks/ContentCardWithAndWithoutImage/ContentCardWithAndWithoutImage.stories.mdx
- stories/Organism/Blocks/ContentCardWithAndWithoutImage/contentcardwithandwithoutimage.scss
[UND-441][DEVELOP] - Single content card feedback issue
> Single content card feedback issue

- stories/Atom/Base-typography/Blockquote/blockquote.scss
- stories/Atom/Base-typography/Blockquote/blockquote.stories.mdx
- stories/Molecules/Text/BlockquoteComponent/BlockquoteComponent.stories.mdx
- stories/Molecules/Text/SmallCopy/smallcopy.scss
- stories/assets/scss/_typography.scss
> [UNDP-899][DEVELOP]: Typography Ui Issues Fixed

- stories/Components/UIcomponents/Accordion/Accordion.stories.mdx
- stories/Components/UIcomponents/Accordion/accordion.scss
- stories/Molecules/FooterNavigation/FooterLists/FooterLists.jsx
- stories/Molecules/FooterNavigation/FooterLists/footerLists.scss
- stories/Organism/Footer/Footer.jsx
- stories/assets/js/accordion.js
Do not merge 
Pr have accordion component changes and footer accordion changes
Dev Unit Testing Videos: Accordion Component: https://www.awesomescreenshot.com/video/6828740?key=5570f8053c5ec7bc29b71af91dabef05
Footer Mobile Accordion: https://www.awesomescreenshot.com/video/6828786?key=86de8e0f23b959fa6ec7b0d1d6d8e1ea
> UNDP-658: UAT code feedback - Organism  | Footer

- stories/Components/UIcomponents/Tab/Tab.jsx
- stories/Components/UIcomponents/Tab/tab.scss
- stories/assets/js/tabs.js
> UND-608-Tab-wrapper

- stories/Atom/Images/Authorimage/Authorimages.jsx
- stories/Atom/Images/Authorimage/Authorimages.stories.mdx
- stories/Atom/Images/Authorimage/authorimage.scss
- stories/Components/UIcomponents/Cards/ContentCard/contentcard.scss
- stories/Organism/Blocks/ContentCardWithAndWithoutImage/contentcardwithandwithoutimage.scss
- stories/assets/scss/_typography.scss
[UND-897][DEVELOP] - Language change issue
> UND-897 Language change issue

- stories/Atom/Typography/Links/link.jsx
- stories/Atom/Typography/Links/link.stories.mdx
- stories/assets/scss/_typography.scss
> UND-898-Heading-issues

- stories/Components/UIcomponents/Cards/BioCard/biocard.scss
> bio-card-issue

- stories/Components/UIcomponents/Gallery/LightboxGallery/lightbox.scss
- stories/Components/UIcomponents/Modal/modal.scss
- stories/Utilities/FrostedImage/FrostedImage.jsx
- stories/Utilities/FrostedImage/frostedimage.scss
[UNDP-908][DEVELOP]: Update class name frosted-background
> [UNDP-908][DEVELOP]: Update class name frosted-background

- stories/Components/UIcomponents/Buttons/Chips/chips.scss
[UNDP-905][DEVELOP]: Update chip placement
> [UNDP-905][DEVELOP]: Update chip placement

- stories/Components/Navigationcomponents/Sidebar/Sidebar.jsx
- stories/Components/Navigationcomponents/Sidebar/Sidebar.stories.mdx
- stories/Components/Navigationcomponents/Sidebar/sidebar.scss
- stories/Molecules/Sidebar-data/sidebardata.scss
- stories/assets/js/sidebar.js
[UNDP-660][DEVELOP]: Update sidebar active class and create control
> [UNDP-660][DEVELOP]: Update sidebar active class and create control

- stories/Components/UIcomponents/Accordion/accordion.scss
> UND-902-Accordion

- stories/Atom/Table/table.scss
- stories/Atom/Table/table.stories.mdx
> table text

- stories/Components/Forms/ExpandableSearch/SearchExpand.scss
UND-893 close button rtl issue fixed
> und-893 rtl issue fixed

- stories/Components/UIcomponents/Cards/StatsCards/StatsCards.jsx
- stories/Components/UIcomponents/Cards/StatsCards/statscards.scss
- stories/Molecules/Blocks/StatsPanel/statspanel.scss
- stories/Molecules/Sdgmodal/sdgmodal.scss
- stories/Organism/Statscardslider/statscardslider.scss
- stories/Patterns/StatsSlider/statsslider.scss
- stories/Templates/ProjectPage/projectpage.scss
> [UNDP-917][DEVELOP]: Stats Card Class Issues Fixed

- stories/Components/Navigationcomponents/Pagination/Pagination.jsx
> UND-611 ARIA attribute feedback

- stories/Components/Navigationcomponents/Mainnavigation/GlobalHeader/GlobalHeader.jsx
- stories/Components/Navigationcomponents/Mainnavigation/GlobalHeader/GlobalHeader.scss
- stories/Components/Navigationcomponents/Mainnavigation/MegaMenu/MegaMenu.jsx
- stories/Components/Navigationcomponents/Mainnavigation/MegaMenu/MegaMenu.scss
- stories/Components/Navigationcomponents/Menu/Menu.jsx
- stories/Components/UIcomponents/Languageswitcher/Languageswitcher.jsx
- stories/assets/js/lang_switcher.js
- stories/assets/js/navigation.js
- stories/assets/js/navigation_data.js
UND-821 header accessibility fixed
> und-821 header accebility fixed

- stories/Components/Forms/Checkbox/checkbox.scss
- stories/Components/Forms/Inputfields/input_group.scss
- stories/Components/Forms/Newslettersignup/signup.scss
- stories/Components/Forms/Radio/radio.scss
- stories/assets/scss/_mixins.scss
[UNDP-900][DEVELOP]: update input group and manage spacing
> [UNDP-900][DEVELOP]: update input group and mange spacing

- stories/Components/UIcomponents/Gallery/LightboxGallery/LightboxGallery.jsx
- stories/Components/UIcomponents/Gallery/LightboxGallery/lightboxgallery.scss
> lightbox-feedback

- stories/Components/UIcomponents/Buttons/Cta_button/CtaButton.jsx
- stories/Components/UIcomponents/Cards/BioCard/BioCard.jsx
- stories/Components/UIcomponents/Modal/Modal.jsx
- stories/Components/UIcomponents/Modal/Modal.stories.mdx
- stories/assets/js/modal.js
[UNDP-607]: fixed modal component converted it to static to dynamic
In This pr i have done some code refactor for CTA button and also make the modal box dynamic. Here is the latest html markup to use this feature 
example code;
> UNDP-607: fixed modal component converted it static to dynamic

- stories/assets/scss/_typography.scss
> UND-898-spacing

- stories/Atom/Table/table.scss
> Table norwrap for th cell

- stories/Molecules/Blocks/TweetCard/TweetCard.stories.mdx
- stories/Organism/Blocks/TweetPanel/TweetPanel.stories.mdx
[UNDP-369][DEVELOP]: Added animation for the link in the tweet card.
> [UNDP-369][DEVELOP]: Added animation for the link in tweetcard

- stories/Atom/Icons/Icons.stories.mdx
- stories/Atom/Icons/icons.scss
> und-888 icon animation

- stories/Components/Navigationcomponents/Mainnavigation/CountrySiteHeader/CountrySiteHeader.jsx
- stories/Components/Navigationcomponents/Mainnavigation/CountrySiteHeader/CountrySiteHeader.scss
- stories/Components/Navigationcomponents/Mainnavigation/GlobalHeader/GlobalHeader.scss
- stories/Components/Navigationcomponents/Mainnavigation/MegaMenu/MegaMenu.scss
- stories/Components/Navigationcomponents/Mainnavigation/MobileNav/MobileNav.scss
- stories/assets/scss/_mixins.scss
- stories/assets/scss/_variables.scss
> UND-910 header issues fixed

- stories/Components/UIcomponents/Accordion/Accordion.jsx
- stories/Components/UIcomponents/Accordion/Accordion.stories.mdx
- stories/Components/UIcomponents/Accordion/accordion.scss
[UND-937][DEVELOP] - Dev Feedback Issues
> [UND-937][DEVELOP] - Dev Feedback Issues

- stories/Atom/Typography/Links/link.jsx
- stories/Components/Forms/Newslettersignup/signup.scss
- stories/Molecules/FooterNavigation/FooterConditions/FooterConditions.jsx
- stories/Molecules/FooterNavigation/FooterConditions/footerCondition.scss
- stories/Molecules/FooterNavigation/FooterConditions2/FooterConditions2.jsx
- stories/Molecules/FooterNavigation/FooterConditions2/footerCondition2.scss
- stories/Molecules/FooterNavigation/FooterIcons/FooterIcons.jsx
- stories/Molecules/FooterNavigation/FooterIcons/footerIcons.scss
- stories/Molecules/FooterNavigation/FooterLists/FooterLists.jsx
- stories/Molecules/FooterNavigation/FooterLists/footerLists.scss
- stories/Molecules/FooterNavigation/FooterLogo/FooterLogo.jsx
- stories/Molecules/FooterNavigation/FooterLogo/footerLogo.scss
- stories/Organism/Footer/Footer.jsx
- stories/Organism/Footer/FooterTwo.jsx
- stories/Organism/Footer/footer.scss
- stories/Templates/Articlepage/ArticlePage.scss
Footer Dev Code Feedbacks Done
> [UNDP-481][DEVELOP]: Footer Dev Code Feedbacks

- stories/assets/scss/_typography.scss
> UND-950-List

- stories/Components/Forms/Dropdowns/CustomSelect/customselect.scss
- stories/Components/Forms/Dropdowns/Multiselect/multiselect.scss
- stories/Components/Navigationcomponents/Breadcrumbs/breadcrumbs.scss
- stories/Components/Navigationcomponents/Menu/menu.scss
- stories/Components/Navigationcomponents/Pagination/pagination.scss
- stories/Components/Navigationcomponents/Sidebar/sidebar.scss
- stories/Molecules/Blocks/TweetCard/TweetCard.stories.mdx
- stories/Organism/Blocks/TweetPanel/TweetPanel.stories.mdx
[UNDP-896][DEVELOP]: Update navigation spacing.
> [UNDP-896][DEVELOP]: Update navigation spacing

- stories/Molecules/Text/Tertiary/Tertiary.jsx
- stories/Molecules/Text/Tertiary/tertiary.scss
> UND-954-Feedback

- stories/Components/UIcomponents/Author/Authorcard/authorcard.scss
- stories/Components/UIcomponents/Cards/ContentCard/ContentCardImage.jsx
- stories/Components/UIcomponents/Cards/ContentCard/ContentCardWithOutImage.jsx
- stories/Components/UIcomponents/Cards/ContentCard/contentcard.scss
- stories/Molecules/Sdgmodal/sdgmodal.scss
- stories/Organism/Blocks/ContentCardWithAndWithoutImage/ContentCardWithAndWithoutImage.jsx
- stories/Organism/Blocks/ContentCardWithAndWithoutImage/ContentCardWithAndWithoutImage.stories.mdx
- stories/Organism/Blocks/ContentCardWithAndWithoutImage/contentcardwithandwithoutimage.scss
- stories/Patterns/DownloadModal/DownloadModal.jsx
- stories/Patterns/DownloadModal/DownloadModal.stories.mdx
- stories/Templates/GenericPage/GenericPage.jsx
- stories/assets/js/downloadmodal.js
- stories/assets/scss/_typography.scss
> [UNDP-914][DEVELOP]: Content Card Ui Issues Fixed

- stories/Components/UIcomponents/Buttons/Cta_link/Cta_link.jsx
- stories/Molecules/Blocks/TweetCard/TweetCard.stories.mdx
- stories/Organism/Blocks/TweetPanel/TweetPanel.stories.mdx
[UNDP-918][DEVELOP]: update CTA link and tweetcard
> [UNDP-918][DEVELOP]: update CTA link and tweetcard

- stories/Components/Navigationcomponents/Breadcrumbs/breadcrumbs.scss
Fixed spacing issue in Breadcrumbs
> Fixed spacing issue in Breadcrumbs

- stories/Patterns/FilterAndSearchBar/FilterAndSearchBar.scss
- stories/assets/js/filter_seach_bar.js
und-949 counts added on filter
> und-949 counts added on filter

- stories/Components/Navigationcomponents/Menu/menu.scss
- stories/Components/Navigationcomponents/Pagination/pagination.scss
- stories/Components/Navigationcomponents/Sidebar/sidebar.scss
[UNDP-896][DEVELOP]: update spacing for rtl
> [UNDP-896][DEVELOP]: update spacing for rtl

- stories/assets/js/select.js
> und-895 custom Select Issues

- stories/Components/UIcomponents/Cards/StatsCards/StatsCards.jsx
- stories/Components/UIcomponents/Cards/StatsCards/statscards.scss
- stories/Molecules/Blocks/StatsPanel/statspanel.scss
> Removed class stats-card-box

- stories/Molecules/Blocks/DownloadCard/DownloadCard.jsx
- stories/Molecules/Blocks/DownloadCard/DownloadCard.scss
- stories/Molecules/DownloadRow/DownloadRow.jsx
download icon animation on pages
> und-1015 download icon animation fixed on all download cards

- stories/Components/UIcomponents/Cards/FeaturedCards/FeaturedContentCard.jsx
- stories/Components/UIcomponents/Cards/FeaturedCards/featuredContentCard.scss
- stories/Organism/Blocks/FeaturedContentCard/FeaturedCard/featuredcard.scss
>  UND-940-Featured-cards

- stories/Atom/Base-typography/Cite/cite.jsx
[UNDP-1012][DEVELOP]: wrap cite element with P tag.
> [UNDP-1012][DEVELOP]: wrap cite element with P tag

- stories/Components/Forms/Checkbox/Checkbox.jsx
- stories/Components/Forms/Checkbox/checkbox.scss
- stories/Components/Forms/Dropdowns/Multiselect/multiselect.scss
- stories/Components/Forms/Radio/Radio.jsx
- stories/Components/Forms/Radio/radio.scss
- stories/Components/UIcomponents/Cards/StatsCards/StatsCards.jsx
- stories/Components/UIcomponents/Cards/StatsCards/statscards.scss
- stories/Molecules/Blocks/StatsPanel/StatsPanel.jsx
- stories/Molecules/Blocks/StatsPanel/statspanel.scss
- stories/Molecules/DownloadRow/downloadrow.scss
> [UNDP-992][DEVELOP]: Checkbox Radio Fixed

- stories/Atom/Images/Authorimage/authorimage.scss
- stories/Components/UIcomponents/Buttons/Cta_link/Cta_link.jsx
- stories/Components/UIcomponents/Buttons/Cta_link/Cta_link.stories.mdx
- stories/Components/UIcomponents/Cards/ContentCard/ContentCardImage.jsx
- stories/Components/UIcomponents/Cards/ContentCard/ContentCardWithOutImage.jsx
- stories/Components/UIcomponents/Cards/ContentCard/contentcard.scss
- stories/Organism/Blocks/ContentCardWithAndWithoutImage/ContentCardWithAndWithoutImage.jsx
- stories/Organism/Blocks/ContentCardWithAndWithoutImage/ContentCardWithAndWithoutImage.stories.mdx
- stories/Templates/ProjectPage/ProjectPage.stories.mdx
- stories/Templates/ProjectPage/projectpage.scss
- stories/Templates/PublicationPage/publicationpage.scss
- stories/assets/scss/_variables.scss
[UND-441][DEVELOP]- Single content card feedback issue
> Feedback Single content card

- stories/Components/Navigationcomponents/Breadcrumbs/breadcrumbs.scss
- stories/Components/UIcomponents/Hero/Homepagehero/HomepageHero.jsx
- stories/Components/UIcomponents/Hero/Homepagehero/HomepageHero.stories.mdx
- stories/Components/UIcomponents/Hero/Homepagehero/HomepageHeroOption.jsx
- stories/Components/UIcomponents/Hero/Homepagehero/HomepageHeroSplit.jsx
- stories/Components/UIcomponents/Hero/Homepagehero/homepagehero.scss
- stories/Components/UIcomponents/Hero/Pagehero/PageHero.jsx
- stories/Components/UIcomponents/Hero/Pagehero/PageHero.stories.mdx
- stories/Components/UIcomponents/Hero/Pagehero/PageHeroOption.jsx
- stories/Components/UIcomponents/Hero/Pagehero/pagehero.scss
- stories/Components/UIcomponents/Hero/Pageherocards/CountryCardHero.jsx
- stories/Components/UIcomponents/Hero/Pageherocards/CountryCardHero.stories.mdx
- stories/Components/UIcomponents/Hero/Pageherocards/countrycardhero.scss
- stories/Molecules/Blocks/CountryCard/CountryCard.jsx
- stories/Molecules/Blocks/CountryCard/countrycard.scss
- stories/Molecules/Blocks/DownloadCard/DownloadCard.jsx
- stories/Molecules/Blocks/DownloadCard/DownloadCard.scss
- stories/Molecules/DownloadRow/DownloadRow.jsx
- stories/Molecules/FooterNavigation/FooterConditions/footerCondition.scss
- stories/Molecules/FooterNavigation/FooterConditions2/footerCondition2.scss
- stories/Molecules/FooterNavigation/FooterIcons/footerIcons.scss
- stories/Patterns/DownloadModal/DownloadModal.jsx
- stories/Patterns/DownloadModal/DownloadModal.stories.mdx
- stories/Patterns/DownloadModal/downloadmodal.scss
- stories/Templates/CountryHomepage/countryhomepage.scss
- stories/Templates/GenericPage/genericpage.scss
- stories/Templates/GlobalHomepage/globalhomepage.scss
- stories/Templates/LandingPage/genericlandingpage.scss
- stories/Templates/ProjectPage/projectpage.scss
> [UNDP-916][DEVELOP]: Hero Feedback

- stories/Components/Forms/Radio/radio.scss
> [UNDP-992][DEVELOP]: Fixed RTL issue radio

- stories/Atom/Table/table.scss
> UND-886-table-mobile

- stories/Patterns/DownloadModal/DownloadModal.jsx
> [UNDP-627][DEVELOP]: Download Modal Issues

- stories/Atom/Images/Imagecaptioncredit/Imagecaption.jsx
- stories/Atom/Images/Imagecaptioncredit/imagecaption.scss
> Figure image and caption

- stories/Components/UIcomponents/Modal/Modal.jsx
- stories/Components/UIcomponents/Modal/modal.scss
- stories/Patterns/DownloadModal/DownloadModal.jsx
- stories/Patterns/DownloadModal/DownloadModal.stories.mdx
Download Modal Tab Issue Fixed.
> [UNDP-627][DEVELOP]: Download Modal Tab Issue Fixed

- stories/Components/Navigationcomponents/Breadcrumbs/Breadcrumbs.jsx
> UND-935-Breadcrumb

- stories/Components/Forms/Inputfields/input_group.scss
Datepicker Mobile RTL issue fix.
> [UND-934][DEVELOP]: Datepicker Mobile RTL issue fix.

- stories/Atom/Navigation/Sidebar-with-arrow/SidebarWithArrow.jsx
- stories/Atom/Navigation/Sidebar/sidebar.stories.mdx
- stories/Atom/Navigation/Sidebar/sidebarFirstLevel.jsx
- stories/Components/Forms/Inputfields/Input_group.jsx
- stories/Components/Forms/Inputfields/input_group.scss
- stories/Components/Forms/Inputfields/input_group.stories.mdx
- stories/Components/Navigationcomponents/Pagination/pagination.scss
- stories/Components/UIcomponents/Buttons/Chips/chips.scss
- stories/assets/icons/Timesred.svg
[UNDP-934][DEVELOP]: update chip spacing and date input.
> [UNDP-934][DEVELOP]: update chip spacing and date input

- stories/Atom/Icons/icons.scss
- stories/Components/UIcomponents/Buttons/Cta_link/Cta_link.jsx
- stories/Components/UIcomponents/Buttons/Cta_link/cta_link.scss
- stories/Components/UIcomponents/Cards/BioCard/BioCard.jsx
- stories/Components/UIcomponents/Cards/BioCard/biocard.scss
- stories/Components/UIcomponents/Cards/ContentCard/contentcard.scss
- stories/Components/UIcomponents/Cards/FeaturedCards/FeaturedContentCard.jsx
- stories/Components/UIcomponents/Cards/FeaturedCards/featuredContentCard.scss
- stories/Molecules/Blocks/CountryCard/CountryCard.jsx
- stories/Molecules/Blocks/CountryCard/countrycard.scss
- stories/Molecules/Blocks/PublicationCard/PublicationCard.jsx
- stories/Molecules/Blocks/PublicationCard/publicationcard.scss
- stories/Molecules/Sdgmodal/sdgmodal.scss
- stories/Organism/Blocks/ContentCardWithAndWithoutImage/ContentCardWithAndWithoutImage.jsx
- stories/Templates/ProjectPage/projectpage.scss
- stories/assets/scss/_mixins.scss
[UND-888][DEVELOP] - Global Icon Feedback Issue
> [UND-888][DEVELOP] - Global Icon Feedback Issue

- stories/Molecules/DownloadRow/DownloadRow.jsx
- stories/Molecules/DownloadRow/DownloadRow.stories.mdx
- stories/Patterns/DownloadModal/DownloadModal.jsx
- stories/Patterns/DownloadModal/DownloadModal.stories.mdx
- stories/Patterns/DownloadModal/downloadmodal.scss
- stories/assets/js/downloadmodal.js
> [UNDP-1056][DEVELOP]: Form Molecules Issues

- stories/Patterns/StatsSlider/StatsSlider.stories.mdx
- stories/Templates/CountryHomepage/countryhomepage.scss
- stories/assets/js/parallax.js
> Stats card parallax

- stories/Components/UIcomponents/Cards/ImageRevelCTACard/ImageCard.jsx
- stories/Components/UIcomponents/Cards/ImageRevelCTACard/ImageCard.stories.mdx
- stories/Components/UIcomponents/Cards/ImageRevelCTACard/imagecard.scss
- stories/Organism/Blocks/ImageRevealCards/ImageRevealCards.jsx
[UNDP-1055][DEVELOP]: update image reveal card.
> [UNDP-1055][DEVELOP]: update image reveal card

- stories/Components/Forms/Checkbox/Checkbox.jsx
- stories/Molecules/DownloadRow/DownloadRow.jsx
- stories/Molecules/DownloadRow/DownloadRow.stories.mdx
- stories/Patterns/DownloadModal/DownloadModal.jsx
> [UNDP-1066][DEVELOP]: Download Row Ui Issues

- stories/Components/UIcomponents/Buttons/Cta_link/cta_link.scss
[UND-1019][DEVELOP] - Icon animation issue
> [UND-1019][DEVELOP] - Icon animation issue

- stories/Patterns/DownloadModal/downloadmodal.scss
- stories/assets/scss/_mixins.scss
Download Modal RTL Issues fixed
> [UNDP-1079][DEVELOP]: Download Modal RTL Issues

- stories/Molecules/Blocks/DownloadCard/DownloadCard.jsx
- stories/Molecules/Blocks/DownloadCard/DownloadCard.scss
> UND-1076-Download-Cards

- stories/Molecules/FooterNavigation/FooterConditions/footerCondition.scss
- stories/Molecules/FooterNavigation/FooterConditions2/footerCondition2.scss
- stories/Molecules/FooterNavigation/FooterIcons/footerIcons.scss
> [UNDP-1078][DEVELOP]: Footer RTL Issues Fixed

- stories/Components/Forms/Checkbox/checkbox.scss
- stories/Patterns/DownloadModal/downloadmodal.scss
- stories/assets/scss/_mixins.scss
Download Modal RTL Issues Fixed.
> [UNDP-1082][DEVELOP]: Download Modal RTL Issues

- stories/Components/UIcomponents/Gallery/LightboxGallery/LightboxGallery.jsx
- stories/Components/UIcomponents/Gallery/LightboxGallery/LightboxGallery.stories.mdx
- stories/Components/UIcomponents/Gallery/LightboxGallery/lightbox.scss
- stories/Components/UIcomponents/Gallery/LightboxGallery/lightboxgallery.scss
- stories/assets/js/lightbox-gallery.js
> UND-1071-light-box-data

- stories/Components/UIcomponents/Cards/BioCard/BioCard.jsx
> UND-709-bio-card

- stories/Components/UIcomponents/Cards/ParallaxCard/ParallaxCards.jsx
- stories/Components/UIcomponents/Carousel/FixedSizeCarousel/FixedSizeCarousel.jsx
- stories/Components/UIcomponents/Carousel/FluidImageSizeCarousel/FluidImageSizeCarousel.jsx
- stories/Components/UIcomponents/Carousel/ImageOnlyCarousel/ImageOnlyCarousel.jsx
- stories/Components/UIcomponents/Gallery/ParallaxGallery/ParallaxGallery.jsx
- stories/Components/UIcomponents/Gallery/ParallaxGallery/parallaxgallery.scss
- stories/Components/UIcomponents/Hero/Pageherocards/CountryCardHero.jsx
- stories/Components/UIcomponents/Hero/Pageherocards/countrycardhero.scss
- stories/Molecules/Blocks/CountryCard/countrycard.scss
- stories/Organism/Statscardslider/Statscardslider.jsx
- stories/Organism/Statscardslider/statscardslider.scss
- stories/Patterns/StatsSlider/StatsSlider.jsx
- stories/Patterns/StatsSlider/statsslider.scss
- stories/assets/js/parallax.js
- stories/assets/js/swiper.js
- stories/assets/scss/_swiper.scss
Fixes the Parallax and Swiper Slider in all devices and RTL.
> [UND-1060][DEVELOP]: Carousel UI Issues.

- stories/Components/UIcomponents/Buttons/Cta_link/cta_link.scss
- stories/Components/UIcomponents/Cards/ImageRevelCTACard/imagecard.scss
- stories/Molecules/Blocks/DownloadCard/DownloadCard.scss
> [UNDP-1083][DEVELOP]:RTL Icons Issues Fixed

- stories/Molecules/Blocks/DownloadCard/DownloadCard.scss
- stories/Molecules/Blocks/StatsPanel/statspanel.scss
> Und 1084 color rtl issue

- stories/Components/UIcomponents/Cards/ImageRevelCTACard/imagecard.scss
- stories/Organism/Blocks/ImageRevealCards/imagerevealcards.scss
[UNDP-1081][DEVELOP]: update chevron spacing for image reveal card.
> [UNDP-1081][DEVELOP]: update chevron spacing for image reveal card.

- stories/Atom/Base-typography/base-typography.stories.mdx
- stories/Components/UIcomponents/Cards/ParallaxCard/ParallaxCards.jsx
- stories/Components/UIcomponents/Carousel/FixedSizeCarousel/FixedSizeCarousel.jsx
- stories/Components/UIcomponents/Carousel/FluidImageSizeCarousel/FluidImageSizeCarousel.jsx
- stories/Components/UIcomponents/Carousel/ImageOnlyCarousel/ImageOnlyCarousel.jsx
- stories/Components/UIcomponents/Hero/Pageherocards/CountryCardHero.jsx
- stories/Components/UIcomponents/Hero/Pageherocards/countrycardhero.scss
- stories/Molecules/Blocks/CountryCard/CountryCard.jsx
- stories/Molecules/Blocks/CountryCard/countrycard.scss
- stories/Organism/Statscardslider/Statscardslider.jsx
- stories/Patterns/StatsSlider/StatsSlider.jsx
Country Card Arrow Issues Fixed.
> [UNDP-948][DEVELOP]: Country Card Arrow Issues

- stories/Components/Forms/Inputfields/input_group.scss
- stories/Organism/Statscardslider/statscardslider.scss
- stories/assets/js/sidebar.js
[UNDP-609][DEVELOP]: Added background for date input.
> [UNDP-609][DEVELOP]: Added background for date input

- stories/Organism/Statscardslider/statscardslider.scss
- stories/assets/scss/_swiper.scss
Carousels scroll width for desk
> Carousels scroll width for desk

- stories/Components/Forms/Dropdowns/Multiselect/MultiSelect.jsx
- stories/Patterns/FilterAndSearchBar/FilterAndSearchBar.jsx
- stories/Patterns/FilterAndSearchBar/FilterAndSearchBar.scss
- stories/assets/js/filter_seach_bar.js
> und-1057, 145

- stories/Components/Navigationcomponents/Mainnavigation/CountrySiteHeader/CountrySiteHeader.jsx
- stories/Components/Navigationcomponents/Mainnavigation/GlobalHeader/GlobalHeader.jsx
- stories/Components/Navigationcomponents/Mainnavigation/GlobalHeader/GlobalHeader.scss
- stories/Components/Navigationcomponents/Mainnavigation/MegaMenu/MegaMenu.scss
- stories/Components/Navigationcomponents/Mainnavigation/MobileNav/MobileNav.jsx
- stories/Components/Navigationcomponents/Mainnavigation/MobileNav/MobileNav.scss
- stories/assets/js/navigation.js
- stories/assets/js/navigation_data.js
- stories/assets/scss/_mixins.scss
- stories/assets/scss/_variables.scss
und-911 header mega menu animation
> und-911 header

- stories/Templates/CountryHomepage/countryhomepage.scss
Stats card spacing issue in templates
> Stats card spacing issue in templates

- stories/Molecules/Blocks/DownloadCard/DownloadCard.scss
> Fixed Download Card RTL Icon

- stories/Components/Forms/Inputfields/input_group.scss
[UNDP-609][DEVELOP]: Added background color for date input
> [UNDP-609][DEVELOP]: Added background color for date input

- stories/Components/UIcomponents/Buttons/Chips/chips.scss
[UNDP-1072][DEVELOP]: update spacing for the chip.
> [UNDP-1072][DEVELOP]: update spacing for the chip

- stories/Components/UIcomponents/Buttons/Chips/chips.scss
[UNDP-1072][DEVELOP]: update spacing of chip for the Burmese language
> [UNDP-1072][DEVELOP]: update spacing of chip for the Burmese language

- README.md
Update readme with File references
> Update readme with File references

- stories/Components/UIcomponents/Cards/ContentCard/ContentCardImage.jsx
- stories/Components/UIcomponents/Cards/ContentCard/content-card.scss
- stories/Components/UIcomponents/Gallery/LightboxGallery/lightbox-gallery.scss
- stories/Molecules/Sdgmodal/Sdgmodal.jsx
- stories/Molecules/Sdgmodal/sdgmodal.scss
- stories/Organism/Text/ProjectDetail/project-detail.scss
- stories/Templates/SDG/sdg.scss
- stories/assets/js/lightbox-gallery.js
> UND-1080-code

- .storybook/preview.js
- stories/Atom/Base-typography/base-typography.stories.mdx
- stories/Components/Forms/Inputfields/input_group.stories.mdx
- stories/Components/Forms/Textpanel/FormTypes.stories.mdx
- stories/Components/UIcomponents/Cards/StatsCards/StatsCards.stories.mdx
- stories/Organism/Blocks/ContentCard/ContentCard.stories.mdx
- stories/Templates/Authors/Authors.stories.mdx
> [UNDP-1091][DEVELOP]: Update TOC

- stories/Atom/Logo/logo.stories.mdx
> Update TOC for logos

- stories/Components/Forms/Dropdowns/CustomSelect/custom-select.scss
- stories/Components/Forms/Dropdowns/Multiselect/multi-select.scss
- stories/Components/Forms/ExpandableSearch/search-expand.scss
- stories/Components/Forms/Newslettersignup/signup.scss
- stories/Components/Navigationcomponents/Mainnavigation/CountrySiteHeader/country-site-header.scss
- stories/Components/Navigationcomponents/Mainnavigation/GlobalHeader/global-header.scss
- stories/Components/Navigationcomponents/Mainnavigation/MegaMenu/mega-menu.scss
- stories/Components/Navigationcomponents/Mainnavigation/MobileNav/mobile-nav.scss
- stories/Components/Navigationcomponents/Pagination/pagination.scss
- stories/Components/Navigationcomponents/Sidebar/sidebar.scss
- stories/Components/UIcomponents/Accordion/accordion.scss
- stories/Components/UIcomponents/Cards/FeaturedCards/featured-content-card.scss
- stories/Components/UIcomponents/Cards/ImageRevelCTACard/image-card.scss
- stories/Components/UIcomponents/Gallery/LightboxGallery/lightbox-gallery.scss
- stories/Components/UIcomponents/Modal/modal.scss
- stories/Organism/Footer/footer.scss
- stories/Utilities/FrostedImage/frosted-background.scss
- stories/assets/scss/_mixins.scss
> UND-870-global

- stories/Components/UIcomponents/Cards/BioCard/bio-card.scss
- stories/Components/UIcomponents/Cards/ContentCard/content-card.scss
- stories/Components/UIcomponents/Cards/FeaturedCards/featured-content-card.scss
- stories/Components/UIcomponents/Cards/ImageRevelCTACard/image-card.scss
- stories/assets/icons/arrow-left-expand-defaut.svg
- stories/assets/scss/_mixins.scss
[UNDP-1093][DEVELOP]: Update chevron of CTA link
> [UNDP-1093][DEVELOP]: Update chevron of CTA link

- stories/assets/js/lightbox-gallery.js
> caption issue on develop

- stories/Components/UIcomponents/Cards/BioCard/bio-card.scss
- stories/Components/UIcomponents/Modal/modal.scss
- stories/Patterns/DownloadModal/DownloadModal.jsx
- stories/Patterns/DownloadModal/download-modal.scss
- stories/Utilities/Scroll-bar/ScrollBar.jsx
- stories/Utilities/Scroll-bar/ScrollBar.stories.mdx
- stories/assets/scss/_base.scss
> UND-1104-Scroll

- stories/Components/UIcomponents/Cards/StatsCards/stats-cards.scss
- stories/assets/scss/_variables.scss
> und-1111 Tab view> Stats Cards Panel

- stories/Templates/CountryHomepage/CountryHomepage.stories.mdx
- stories/Templates/CountryHomepage/countryhome-page.scss
[UND-1101][DEVELOP] - RTL and Language issue
> [UND-1101][DEVELOP] - RTL and Language issue

- stories/Components/Navigationcomponents/Mainnavigation/MobileNav/MobileNav.jsx
- stories/Molecules/ParallaxCard/ParallaxCard.jsx
- stories/assets/icons/arrow-left-expand-defaut.svg
- stories/assets/scss/_mixins.scss
[UNDP-1098][DEVELOP]: added chevron on the global homepage for menu
> [UNDP-1098][DEVELOP]: added chevron on the global homepage for menu

- stories/Templates/SDG/Sdg.stories.mdx
> [UNDP-1102][DEVELOP]: SDG language Correct

- stories/Components/UIcomponents/Author/Authorcard/author-card.scss
- stories/Templates/Authors/Authors.scss
> [UNDP-1105][DEVELOP]: Author UNDP Template

- stories/assets/icons/arrow-left-expand-defaut.svg
- stories/assets/scss/_mixins.scss
[UNDP-1093][DEVELOP]: update chevron
> [UNDP-1093][DEVELOP]: update chevron

- stories/Components/UIcomponents/Buttons/Cta_button/buttons.scss
- stories/assets/js/select.js
- stories/assets/scss/_mixins.scss
und-1077 UAT Feedback - Form | Organisms
> und-1077 UAT Feedback - Form | Organisms

- stories/Components/Forms/Dropdowns/Multiselect/multi-select.scss
> und-1077 bug fixed

- stories/Components/Navigationcomponents/Sidebar/sidebar.scss
- stories/Components/UIcomponents/Buttons/Cta_link/cta-link.scss
- stories/Components/UIcomponents/Cards/ContentCard/content-card.scss
- stories/Templates/GenericPage/generic-page.scss
- stories/assets/scss/_mixins.scss
[UNDP-1117][DEVELOP]: update spacing for generic page
> update spacing for generic page

- stories/Molecules/Sdgmodal/sdgmodal.scss
- stories/assets/scss/_mixins.scss
> UND-1147-SDG-RTL

- stories/Organism/Blocks/ContentCard/ContentCard.stories.mdx
- stories/Templates/AuthorPage/AuthorPage.jsx
- stories/Templates/AuthorPage/AuthorPage.stories.mdx
- stories/Templates/GenericPage/generic-page.scss
[UNDP-1153][DEVELOP]: update content card
> [UNDP-1153][DEVELOP]: update content card

- stories/Components/UIcomponents/Buttons/Cta_button/buttons.scss
- stories/Molecules/Sdgmodal/Sdgmodal.jsx
> [UNDP-1158][DEVELOP]: Border Remove

- stories/Organism/Footer/footer.scss
- stories/Templates/LandingPage/GenericLandingPage.jsx
- stories/Templates/LandingPage/GenericLandingPage.stories.mdx
- stories/Templates/LandingPage/generic-landing-page.scss
[UND-1159][DEVELOP] - Generic Landing page regression issues
> Generic Landing page regression

- stories/Components/Forms/Dropdowns/Multiselect/multi-select.scss
- stories/assets/scss/_mixins.scss
> und-1160 Patterns  > Filter and search bar > Border and alignment issues

- stories/Organism/Footer/Footer.stories.mdx
- stories/Templates/Articlepage/ArticlePage.stories.mdx
- stories/assets/scss/_typography.scss
[UNDP-1118][DEVELOP]: update article page
> [UNDP-1118][DEVELOP]: update article page

- stories/Components/UIcomponents/Hero/Pagehero/PageHero.stories.mdx
[UNDP-1174][DEVELOP]: Update text for the Japanese language
> [UNDP-1174][DEVELOP]:Update text for the Japanese language

- stories/Components/UIcomponents/Cards/FeaturedCards/FeaturedContentCard.stories.mdx
- stories/Components/UIcomponents/Cards/FeaturedCards/featured-content-card.scss
> und-1172 Components > UI Components > Cards > Featured cards issue

- stories/Molecules/Blocks/CountryCard/country-card.scss
> und-1173 UI Components > Hero > Page hero Cards - Chevron Icon Issue

- stories/Organism/Blocks/FeaturedContentCard/PagewideContentCard/PageWideCard.jsx
- stories/Organism/Blocks/FeaturedContentCard/PagewideContentCard/PageWideCard.stories.mdx
- stories/Organism/Blocks/FeaturedContentCard/PagewideContentCard/page-wide-card.scss
[UNDP-1183][DEVELOP]: update CSS for page-wide to avoid image stretch
> [UNDP-1183][DEVELOP]: update CSS for page-wide to avoid image stretch

- stories/Components/UIcomponents/Cards/ContentCard/content-card.scss
> 1171-content

- stories/Molecules/Sdgmodal/sdgmodal.scss
[UNDP-1147][DEVELOP]: update sdg page bullets spacing
> [UNDP-1147][DEVELOP]: update sdg page bullets spacing

- stories/Components/UIcomponents/Hero/Pagehero/page-hero.scss
- stories/Molecules/Blocks/DownloadCard/DownloadCard.jsx
- stories/Molecules/Blocks/DownloadCard/DownloadCard.stories.mdx
- stories/Molecules/Blocks/DownloadCard/download-card.scss
- stories/Templates/LandingPage/generic-landing-page.scss
- stories/Templates/ProjectPage/ProjectPage.jsx
- stories/Templates/ProjectPage/ProjectPage.stories.mdx
- stories/Templates/ProjectPage/project-page.scss
[UND-1164][DEVELOP] - Project Page Regression
> Project Page Regression

- stories/Organism/Blocks/FeaturedContentCard/PagewideContentCard/page-wide-card.scss
[UNDP-1182][DEVELOP]: remove the yellow class from page-wide
> [UNDP-1182][DEVELOP]: remove the yellow class from page-wide

- stories/Components/Forms/Dropdowns/Multiselect/multi-select.scss
> und-1181 UAT feedback - Forms | Atoms | Select - Multi select

- stories/Atom/Cards/Card-thumbnail/CardThumbnail.jsx
- stories/Atom/Cards/Publication-thumbnail/PublicationThumbnail.jsx
- stories/Atom/Cards/Publication-thumbnail/publication-thumbnail.scss
- stories/Components/UIcomponents/Cards/BioCard/BioCard.jsx
- stories/Components/UIcomponents/Cards/FeaturedCards/FeaturedContentCard.jsx
- stories/Molecules/Blocks/DownloadCard/DownloadCard.jsx
- stories/Molecules/Blocks/DownloadCard/download-card.scss
- stories/Molecules/Blocks/PublicationCard/PublicationCard.jsx
- stories/Molecules/Blocks/PublicationCard/publication-card.scss
> UND-1178-Download

- stories/Components/Forms/Dropdowns/CustomSelect/CustomSelect.jsx
- stories/assets/js/select.js
@shishirphadke I have changed select JS totally because it is not working properly and unnecessary script there.
> und-1180 UAT Feedback - (P0) - Forms | Atoms | Select - Single select

- stories/assets/scss/_variables.scss
[UNDP-1190][DEVELOP]: update gradient for stats
> [UNDP-1190][DEVELOP]: update gradient for stats

- stories/Components/Forms/Inputfields/input-group.scss
[UNDP-1194][DEVELOP]: update input group spacing and font-family
> [UNDP-1194][DEVELOP]: update input group spacing and font-family

- stories/Components/Forms/Inputfields/input-group.scss
- stories/Components/Forms/Textpanel/form-types.scss
Components > Forms > Text Panel > Spacing Issues
> und-1195 Components > Forms > Text Panel > Spacing Issues

- stories/Molecules/Blocks/CountryCard/country-card.scss
> hero country

- stories/Components/UIcomponents/Languageswitcher/language-switcher.scss
[UNDP-1190][DEVELOP]: update color for language switcher
> [UNDP-1190][DEVELOP]: update color for language switcher

- stories/Components/Forms/Newslettersignup/signup.scss
[UND-1159][DEVELOP] - Footer Issue
> [UND-1159][DEVELOP] - Footer Issue

- stories/Components/UIcomponents/Buttons/Cta_button/CtaButton.stories.mdx
- stories/Components/UIcomponents/Tab/tab.scss
[UNDP-1204][DEVELOP]: Update text for button and spacing for tabs
> [UNDP-1204][DEVELOP]: Update text for button and spacing for tabs

- stories/Templates/Authors/Authors.scss
- stories/Templates/Authors/Authors.stories.mdx
> und-1205 Author details - total six in row

- stories/Molecules/Text/HeadingBig/HeadingBig.stories.mdx
[UNDP-1206][DEVELOP]: Update our mission text
> [UNDP-1206][DEVELOP]: Update our mission text

- stories/Components/UIcomponents/Hero/Pageherocards/country-card-hero.scss
[UNDP-1209][DEVELOP]: update spacing for page hero
> [UNDP-1209][DEVELOP]: update spacing for page hero

- stories/Molecules/DownloadRow/DownloadRow.jsx
- stories/Molecules/DownloadRow/download-row.scss
> Form Molecules

- stories/Atom/Navigation/Menu-items/menu-items.scss
- stories/Components/Navigationcomponents/Breadcrumbs/breadcrumbs.scss
[UNDP-1210][DEVELOP]: Update breadcrumb letter spacing
> [UNDP-1210][DEVELOP]: Update breadcrumb letter spacing

- README.md
- stories/Components/UIcomponents/Cards/BioCard/BioCard.stories.mdx
- stories/Organism/Blocks/ContentCard/ContentCard.stories.mdx
- stories/Organism/Blocks/ContentCardWithAndWithoutImage/ContentCardWithAndWithoutImage.stories.mdx
- stories/Organism/Blocks/FeaturedContentCard/FeaturedCard/FeaturedCard.stories.mdx
- stories/Organism/Blocks/ImageRevealCards/ImageRevealCards.stories.mdx
[UNDP-1211][DEVELOP]: Update Toc for cards
> [UNDP-1211][DEVELOP]: Update Toc for cards

- stories/Components/UIcomponents/Languageswitcher/language-switcher.scss
[UNDP-1218][DEVELOP]: update font family for the Burmese language
> [UNDP-1218][DEVELOP]: update font family for Burmese language

- stories/Templates/PublicationPage/PublicationPage.jsx
- stories/Templates/PublicationPage/publication-page.scss
- stories/assets/js/sticky.js
> und-1208 Templates > Publication Page - Multiple Issues

- .storybook/preview-head.html
[UNDP-1219][DEVELOP]: Update color for code.
> [UNDP-1219][DEVELOP]: Update color for code.

- stories/Molecules/DownloadRow/DownloadRow.jsx
> select checkbox by tab button

- stories/Components/UIcomponents/Languageswitcher/language-switcher.scss
[UNDP-1239][DEVELOP]: Added color on hover for language switcher
> [UNDP-1239][DEVELOP]: Added color on hover for language switcher

- stories/Atom/Logo/Logo.stories.mdx
- stories/Molecules/Imagecaption/Imagecaption.jsx
[UNDP-1238][DEVELOP]: Update logo and imagecaption
> [UNDP-1238][DEVELOP]: Update logo and imagecaption

- stories/Molecules/Blocks/CountryCard/country-card.scss
> Hero page card

- stories/Components/Navigationcomponents/Mainnavigation/MobileNav/mobile-nav.scss
> und-1236 UAT Feedback - Navigation | Organism - 4 (Mobile menu panel)

- stories/Components/Navigationcomponents/Mainnavigation/CountrySiteHeader/CountrySiteHeader.jsx
- stories/Components/Navigationcomponents/Mainnavigation/CountrySiteHeader/country-site-header.scss
- stories/Components/Navigationcomponents/Mainnavigation/GlobalHeader/GlobalHeader.jsx
- stories/Components/Navigationcomponents/Mainnavigation/GlobalHeader/global-header.scss
- stories/Components/Navigationcomponents/Mainnavigation/MobileNav/mobile-nav.scss
- stories/assets/js/navigation.js
- stories/assets/scss/_mixins.scss
> und-1230 UAT Feedback - Navigation | Organism - 2 (Country Site Header)

- stories/Molecules/Text/HeadingBig/HeadingBig.jsx
- stories/Molecules/Text/HeadingBig/headingbig.scss
- stories/Templates/CountryHomepage/CountryHomepage.jsx
- stories/Templates/CountryHomepage/countryhome-page.scss
- stories/Templates/GlobalHomepage/globalhome-page.scss
- stories/Templates/ProjectPage/project-page.scss
- stories/assets/js/smooth-bg-change.js
- stories/assets/scss/_variables.scss
[UND-1100][DEVELOP]- Country Homepage regression Issue
> Country Homepage regression

- stories/Components/Navigationcomponents/Mainnavigation/CountrySiteHeader/CountrySiteHeader.jsx
- stories/Components/Navigationcomponents/Mainnavigation/CountrySiteHeader/CountrySiteHeader.stories.mdx
- stories/Components/Navigationcomponents/Mainnavigation/GlobalHeader/GlobalHeader.jsx
- stories/Components/Navigationcomponents/Mainnavigation/GlobalHeader/GlobalHeader.stories.mdx
- stories/Components/UIcomponents/LanguageSwitcher/LanguageSwitcher.jsx
- stories/Components/UIcomponents/LanguageSwitcher/LanguageSwitcher.stories.mdx
- stories/Components/UIcomponents/LanguageSwitcher/language-switcher.scss
- stories/Templates/ArticlePage/ArticlePage.stories.mdx
- stories/Templates/AuthorPage/AuthorPage.stories.mdx
- stories/Templates/Authors/Authors.stories.mdx
- stories/Templates/CountryHomepage/CountryHomepage.stories.mdx
- stories/Templates/GenericPage/GenericPage.stories.mdx
- stories/Templates/GlobalHomepage/GlobalHomepage.stories.mdx
- stories/Templates/LandingPage/GenericLandingPage.stories.mdx
- stories/Templates/ProjectPage/ProjectPage.stories.mdx
- stories/Templates/PublicationPage/PublicationPage.stories.mdx
- stories/Templates/Sdg/Sdg.stories.mdx
- stories/assets/scss/style.scss
UND-1201-js-component-change-part-4
>  UND-1201-js-component-change-part-4

- stories/Atom/BaseTypography/BaseTypography.stories.mdx
- stories/Atom/Logo/Logo.stories.mdx
- stories/Molecules/Blocks/DownloadCard/DownloadCard.stories.mdx
[UNDP-1219][DEVELOP]: Update docs navigation of typography
> [UNDP-1219][DEVELOP]: Update docs navigation of typography

- stories/Components/Forms/Dropdowns/Multiselect/MultiSelect.jsx
- stories/Components/Forms/Dropdowns/Multiselect/MultiSelect.stories.mdx
> und-1245 Dev feedback - Forms | Atoms | Select - Multi select

- stories/Components/UIcomponents/Gallery/LightboxGallery/lightbox-gallery.scss
- stories/Molecules/ImageCaption/ImageCaption.jsx
> lightbox-issue

- stories/Components/Forms/Dropdowns/CustomSelect/custom-select.scss
> UND-1255-custom-select

- stories/Components/Forms/InputFields/InputFields.jsx
- stories/Components/Forms/InputFields/input-fields.scss
- stories/Components/Forms/SearchExpand/search-expand.scss
- stories/Components/Forms/TextPanel/text-panel.scss
- stories/Components/Forms/Textarea/Textarea.jsx
[UND-1166][DEVELOP]- Forms-Organism
> [UND-1166][DEVELOP]- Forms-Organism

- stories/Components/UIcomponents/Buttons/Chips/chips.scss
[UNDP-145][DEVELOP]: Update chip chevron spacing
> [UNDP-145][DEVELOP]: Update chip chevron spacing

- stories/Organism/Footer/Footer.jsx
> footer missing in templates

- stories/Components/Navigationcomponents/Mainnavigation/CountrySiteHeader/country-site-header.scss
- stories/Components/Navigationcomponents/Mainnavigation/MobileNav/mobile-nav.scss
> Country Site Header

- stories/Components/Forms/TextPanel/text-panel.scss
- stories/Components/UIcomponents/Buttons/Chips/chips.scss
- stories/Molecules/ImageCaption/ImageCaption.jsx
[UNDP-1166][DEVELOP]: Update text panel button font size for Burmese language
> [UNDP-1166][DEVELOP]: Update text panel button font size for Burmese language

- stories/Templates/ArticlePage/article-page.scss
[UND-1269][DEVELOP]-Article Page Spacing Issue
> [UND-1269][DEVELOP]-Article Page Spacing Issue

- stories/Molecules/Blocks/CountryCard/country-card.scss
[UND-1187][DEVELOP]- CTA Link Animation Issue
> [UND-1187][DEVELOP]- CTA Link Animation Issue

- stories/Atom/Images/Image/Image.jsx
- stories/Templates/ArticlePage/ArticlePage.jsx
- stories/assets/js/lazyload.js
> und-1268 Template > Article Page Issues

- stories/Components/Forms/SearchExpand/SearchExpand.stories.mdx
- stories/Components/Forms/TextPanel/TextPanel.stories.mdx
document for textpanel & expandsearch
> document for textpanel & expandsearch

- stories/Components/Forms/Checkbox/Checkbox.stories.mdx
- stories/Components/Forms/Dropdowns/CustomSelect/CustomSelect.stories.mdx
- stories/Components/Forms/Dropdowns/Multiselect/MultiSelect.stories.mdx
- stories/Components/Forms/InputFields/InputFields.stories.mdx
- stories/Components/Forms/Radio/Radio.stories.mdx
> document-for-components-forms

- stories/Organism/Blocks/AuthorSummary/author-summary.scss
- stories/Templates/AuthorPage/AuthorPage.jsx
- stories/Templates/AuthorPage/author-page.scss
[UND-1308][DEVELOP] -  author page issues
> author page issues

- stories/Components/UIcomponents/Cards/FeaturedCard/FeaturedContentCard.jsx
- stories/Components/UIcomponents/Cards/FeaturedCard/featured-content-card.scss
- stories/Components/UIcomponents/Cards/StatsCards/stats-cards.scss
- stories/Components/UIcomponents/Hero/PageHero/PageHero.stories.mdx
- stories/Organism/Blocks/ContentCardWithAndWithoutImage/ContentCardWithAndWithoutImage.stories.mdx
- stories/Organism/Blocks/FeaturedContentCard/FeaturedCard/FeaturedCard.stories.mdx
- stories/Patterns/StatsSlider/StatsSlider.jsx
- stories/Patterns/StatsSlider/stats-slider.scss
- stories/Templates/CountryHomepage/CountryHomepage.jsx
- stories/Templates/CountryHomepage/CountryHomepage.stories.mdx
- stories/Templates/CountryHomepage/countryhome-page.scss
[UND-1322][DEVELOP]-Country Homepage feedback issue
> [UND-1322][DEVELOP]-Country Homepage feedback issue

- stories/Components/UIcomponents/Hero/PageHero/PageHero.jsx
- stories/Components/UIcomponents/Hero/PageHero/PageHero.stories.mdx
- stories/Components/UIcomponents/Hero/PageHero/page-hero.scss
- stories/assets/js/animation.js
[UNDP-1320][DEVELOP]: Update page hero vertical-align for text
> [UNDP-1320][DEVELOP]: Update page hero vertical-align for text

- stories/Components/Navigationcomponents/Mainnavigation/GlobalHeader/global-header.scss
- stories/Templates/CountryHomepage rtl/CountryHomepage.jsx
- stories/Templates/CountryHomepage rtl/CountryHomepage.stories.mdx
- stories/Templates/CountryHomepage rtl/countryhome-page.scss
- stories/Templates/GlobalHomepage rtl/GlobalHomepage.jsx
- stories/Templates/GlobalHomepage rtl/GlobalHomepage.stories.mdx
- stories/Templates/GlobalHomepage rtl/globalhome-page.scss
@shishirphadke dummy page created to check logo animation on RTL case. Suggested by Aditya. We will remove it after client satisfaction.
> und-1235 dummy component for rtl logo animation

- stories/Components/UIcomponents/Cards/ImageRevelCTACard/image-revel-cta-card.scss
- stories/Molecules/Blocks/StatsPanel/stats-panel.scss
- stories/Molecules/Blocks/TweetCard/tweet-card.scss
- stories/Templates/GenericPage/generic-page.scss
[UNDP-1318][DEVELOP]: Update tweetcard, stats cards section of globalpage
> [UNDP-1318][DEVELOP]: Update tweetcard, stats cards section of globalpage

- stories/Components/Forms/Dropdowns/Multiselect/MultiSelect.stories.mdx
- stories/Components/Forms/InputFields/InputFields.stories.mdx
- stories/Components/Forms/SearchExpand/SearchExpand.stories.mdx
- stories/Components/Forms/TextPanel/TextPanel.stories.mdx
- stories/Components/Forms/Textarea/Textarea.stories.mdx
- stories/Components/Navigationcomponents/Mainnavigation/GlobalHeader/GlobalHeader.stories.mdx
- stories/Components/UIcomponents/Author/AuthorCard/AuthorCard.stories.mdx
- stories/Components/UIcomponents/Author/AuthorColumn/AuthorColumn.stories.mdx
- stories/Components/UIcomponents/Cards/ImageRevelCTACard/ImageRevelCTACard.stories.mdx
- stories/Components/UIcomponents/Gallery/LightboxGallery/LightboxGallery.stories.mdx
- stories/Components/UIcomponents/LanguageSwitcher/LanguageSwitcher.stories.mdx
- stories/Organism/Footer/Footer.stories.mdx
Update documentation for components
> und-108 document update

- stories/Templates/CountryHomepage rtl/CountryHomepage.jsx
- stories/Templates/GlobalHomepage rtl/GlobalHomepage.jsx
> und-1235 logo animation

- stories/Components/UIcomponents/Gallery/LightboxGallery/LightboxGallery.stories.mdx
[UND-1213][DEVELOP]- Lightbox gallery document
> [UND-1213][DEVELOP]- Lightbox gallery document

- stories/Components/UIcomponents/Hero/PageHeroCards/pagehero-cards.scss
- stories/Molecules/Blocks/CountryCard/country-card.scss
- stories/assets/js/swiper.js
[UND-1187][DEVELOP]-Page hero cards tablet issue
> [UND-1187][DEVELOP]-Page hero cards tablet issue 

- stories/Components/Navigationcomponents/Sidebar/Sidebar.jsx
- stories/Components/UIcomponents/Hero/PageHero/page-hero.scss
- stories/Templates/GenericPage/GenericPage.jsx
- stories/Templates/GenericPage/generic-page.scss
- stories/Templates/LandingPage/GenericLandingPage.jsx
- stories/Templates/LandingPage/GenericLandingPage.stories.mdx
- stories/Templates/ProjectPage/project-page.scss
- stories/Templates/Sdg/sdg.scss
[UNDP-1332][DEVELOP]: update img and spacing for hero
> [UNDP-1332][DEVELOP]: update img and spacing for hero

- stories/assets/js/lightbox-gallery.js
[UNDP-1312][DEVELOP]: closing the popup by clicking the frosty outer margin
> [UNDP-1312][DEVELOP]: closing the popup by clicking the frosty outer margin

- stories/Components/UIcomponents/Cards/ImageRevelCTACard/ImageRevelCTACard.jsx
- stories/Components/UIcomponents/Cards/ImageRevelCTACard/ImageRevelCTACard.stories.mdx
- stories/Components/UIcomponents/Cards/ImageRevelCTACard/image-revel-cta-card.scss
- stories/assets/js/sticky.js
[UND-1322][DEVELOP] - Hovercolor on reveal cards
> Hovercolor on reveal cards

- stories/Templates/ProjectPage/project-page.scss
@shishirphadke we have removed the "sb-main-padded". It created an issue on mobile so I have made a change please review and merge.
> project page gap on mobile. related to und-1324

- stories/Templates/GenericPage/generic-page.scss
- stories/Templates/GlobalHomepage/GlobalHomepage.jsx
- stories/Templates/GlobalHomepage/globalhome-page.scss
UND-1324 slider on rtl case issue fixed.
> und-1324 rtl issue fixed

- stories/Components/UIcomponents/Cards/ImageRevelCTACard/ImageRevelCTACard.jsx
- stories/Components/UIcomponents/Cards/ImageRevelCTACard/image-revel-cta-card.scss
- stories/Components/UIcomponents/Hero/PageHero/page-hero.scss
- stories/Organism/Blocks/ImageRevealCards/ImageRevealCards.stories.mdx
- stories/Templates/CountryHomepage/CountryHomepage.jsx
- stories/Templates/GlobalHomepage/GlobalHomepage.jsx
- stories/assets/js/smooth-bg-change.js
- stories/assets/scss/_base.scss
[UNDP-1321][DEVELOP]: update bg color spacing for project page
> [UNDP-1321][DEVELOP]: update bg color spacing for project page

- stories/Organism/Blocks/TweetPanel/TweetPanel.jsx
- stories/Templates/GenericPage/generic-page.scss
- stories/Templates/GlobalHomepage rtl/globalhome-page.scss
- stories/Templates/GlobalHomepage/GlobalHomepage.jsx
- stories/Templates/GlobalHomepage/globalhome-page.scss
- stories/Templates/ProjectPage/ProjectPage.jsx
- stories/Templates/ProjectPage/project-page.scss
[UNDP-1318][DEVELOP]: update global homepage padding
> [UNDP-1318][DEVELOP]: update global homepage padding

- stories/Components/Navigationcomponents/Mainnavigation/CountrySiteHeader/country-site-header.scss
- stories/Components/Navigationcomponents/Mainnavigation/GlobalHeader/global-header.scss
> und-1235 UAT Feedback - Navigation | Organisms - 1 (Global Header)

- stories/Molecules/Blocks/CountryCard/CountryCard.jsx
- stories/Molecules/Blocks/CountryCard/country-card.scss
- stories/Molecules/Blocks/DownloadCard/DownloadCard.jsx
- stories/Templates/CountryHomepage/CountryHomepage.stories.mdx
[UND-1187][DEVELOP]-Country Card Touch Hover
> Country Card Touch Hover

- stories/Molecules/Text/HeadingBig/HeadingBig.jsx
- stories/Molecules/Text/HeadingBig/HeadingBig.stories.mdx
- stories/Molecules/Text/HeadingBig/headingbig.scss
- stories/Organism/Blocks/ContentCardWithAndWithoutImage/ContentCardWithAndWithoutImage.jsx
- stories/Organism/Blocks/ContentCardWithAndWithoutImage/ContentCardWithAndWithoutImage.stories.mdx
- stories/Organism/StatsCardSlider/stats-card-slider.scss
- stories/Templates/CountryHomepage/CountryHomepage.jsx
- stories/Templates/GlobalHomepage/GlobalHomepage.jsx
- stories/Templates/ProjectPage/ProjectPage.jsx
- stories/Templates/ProjectPage/project-page.scss
[UND-1353][DEVELOP]- Project page transition issue
> Project page transition issue

- stories/Components/UIcomponents/Cards/ContentCard/content-card.scss
- stories/Components/UIcomponents/Cards/ImageRevelCTACard/ImageRevelCTACard.jsx
- stories/Organism/Blocks/ContentCardWithAndWithoutImage/ContentCardWithAndWithoutImage.stories.mdx
- stories/Templates/CountryHomepage/CountryHomepage.jsx
[UND-1322][DEVELOP]-Reveal card hover color
> [UND-1322][DEVELOP]-Reveal card hover color

- stories/Components/Navigationcomponents/Mainnavigation/GlobalHeader/global-header.scss
[UNDP-1235][DEVELOP]: Removed background color from a search of header
> [UNDP-1235][DEVELOP]: Removed background color from a search of header

- stories/Components/Navigationcomponents/Mainnavigation/CountrySiteHeader/CountrySiteHeader.jsx
- stories/Components/Navigationcomponents/Mainnavigation/GlobalHeader/GlobalHeader.jsx
- stories/assets/js/navigation-data.js
- stories/assets/js/navigation.js
@shishirphadke I have made the changes on header js as per discussion with @kuldev Please review and merge.
> header js changes as per discussion

- stories/Templates/PublicationPage/publication-page.scss
[UND-1323][DEVELOP]-Publication page hover issue
> Publication page hover issue

- stories/Components/UIcomponents/Cards/FeaturedCard/FeaturedContentCard.jsx
- stories/Molecules/Blocks/PublicationCard/publication-card.scss
- stories/Templates/PublicationPage/publication-page.scss
> featured card organism change

- stories/Components/UIcomponents/Cards/FeaturedCard/FeaturedContentCard.jsx
Featured Content card undefined class fix
> Featured Content card undefined class fix

- stories/Components/Navigationcomponents/Mainnavigation/GlobalHeader/GlobalHeader.stories.mdx
header logo on doc issue fixed
> header logo on doc issue fixed

- stories/Atom/Table/Table.stories.mdx
- stories/Atom/Typography/Links/Links.stories.mdx
> css file extention to min.css in docs

- stories/Templates/GenericPage/GenericPage.jsx
- stories/Templates/GenericPage/generic-page.scss
- stories/Templates/PublicationPage/PublicationPage.jsx
- stories/assets/js/sticky.js
> UNDP-1340-genric-sticky

- stories/Atom/Icons/icons.scss
> Download icon

- stories/Components/Navigationcomponents/Mainnavigation/CountrySiteHeader/country-site-header.scss
#933 - Set site title line height to match figma specs
> #933 site title line height is incorrect

- stories/Components/UIcomponents/Hero/HomePageHero/HomePageHero.stories.mdx
> #1108 - typo fix

- stories/Molecules/FooterNavigation/FooterLists/FooterLists.jsx
- stories/Organism/Footer/Footer.jsx
- stories/Organism/Footer/footer.scss
#984 
Setup of footer section to be able to adjust to a dynamic amount of primary menu items and sub items.
> #984 -- Setup of footer section to be able to adjust to a dynamic amount of primary menu items and their sub items.

- stories/Templates/GenericPage/GenericPage.jsx
#918
Remove progress bar from header and fixed some extra spaces and tab alignment issues with the file.
> #918 progress bar should be removed from the generic page template

- stories/Components/UIcomponents/Tab/tab.scss
#902 
Set tab container to have internal padding, rather than setting the padding on the internal content
> #902 tab container internal padding

- stories/Atom/BaseTypography/Blockquote/blockquote.scss
#925
Set links in blockquotes to respect blockquote styles.
> #925 -- Set links in blockquotes to respect blockquote styles.

- stories/Components/UIcomponents/Modal/modal.scss
- stories/Patterns/DownloadModal/download-modal.scss
#908 
Updated download modal list height, and updated the modal header styles.
> #908 - Download modal style updates

- stories/Components/Navigationcomponents/Sidebar/sidebar.scss
Active parent states on mobile are now blue bg/white text
> #890 -- Set the active section to be blue/white for mobile state.

- stories/Components/UIcomponents/Buttons/CtaButton/CtaButton.jsx
- stories/Components/UIcomponents/Buttons/CtaButton/CtaButton.stories.mdx
- stories/Components/UIcomponents/Buttons/CtaButton/buttons.scss
#985 - Added new icon options to buttons
Added new download icon and external link icon to primary and secondary buttons, with css updates for disabled and 'rtl' states.
> #985 - Added new icon options to buttons

- stories/Utilities/ScrollBar/scrollbar.scss
- stories/assets/scss/_base.scss
Firefox has many limitations about how a scrollbar can be styled at this time. This is round one attempt to work within the confines of these limitations to make a design that can acceptable.
@theadamparker - For now, this PR is just to create an env where this first round can be viewed.
> #907 -- Styling up scrollbars for firefox

- stories/Components/UIcomponents/Hero/PageHero/PageHero.jsx
- stories/Components/UIcomponents/Hero/PageHero/PageHero.stories.mdx
- stories/Components/UIcomponents/Hero/PageHero/PageHeroOption.jsx
- stories/Components/UIcomponents/Hero/PageHero/PageHeroOption.stories.mdx
- stories/Components/UIcomponents/Hero/PageHero/page-hero.scss
#905 - Add option of page hero-full to allow for no background image
#997 - Allow for optional CTA link
#1008 - Added setup for optional overline and subtitle fields
> Multiple updates to page hero

- stories/Components/Navigationcomponents/Mainnavigation/MegaMenu/mega-menu.scss
- stories/assets/js/navigation.js
Code came from work on dropdown menu changes.
@Jura, I cleaned up some of the code organization on navigation.js to make it easier to read whats going on. Functionality hasn't changed, just comments and formatting adjusted.
> #915 -- Fix glitchy mega menu panels on global homepage.

- stories/Templates/Sdg/Sdg.stories.mdx
> Fix SDG template typos

- stories/Components/Navigationcomponents/Mainnavigation/CountrySiteHeader/CountrySiteHeaderDropdown.stories.mdx
- stories/Components/UIcomponents/Hero/PageHero/PageHero.stories.mdx
> Fix broken link typo in documetation

- stories/Components/Forms/InputFields/InputFields.jsx
- stories/Components/Forms/InputFields/input-fields.scss
changed the color of the date from gray to black after filling, made the default calendar for chrome
> issue #1330 - Date input corrections
